### ISSUE TITLE
user-bundle with LexikJWTAuthenticationBundle

### ISSUE THREAD

**Issue by DevMDamien** [msgphp/msgphp#111]
Hi,

I'm trying to use the msgphp/user-bundle with api-platform, but I have some difficulties to create a valid jwt with lexik/jwt-authentication-bundle.

After a few time of configuration, I have this (payload) : 
`
 {
  "roles": [],
  "username": "1",
  "iat": 1520941885,
  "exp": 1520945485
}
`

When I'm using for a second time the token, I have an error because the bundle is calling `findByUsername()` with the user id instead of, in my case, the user email.

If I change the code (into MsgPhp\User\Infra\Security\SecurityUser, to let the `getUsername()` function return my email address), I retrieve a valid jwt.
`
 {
  "roles": [],
  "username": "<valid email address>",
  "iat": 1520941885,
  "exp": 1520945485
}
`
and during my second http request, the user is successfully authenticated.

**Comment by ro0NL** [comment]
HI @DevMDamien ,

> I have an error because the bundle is calling findByUsername()

Can you clarify this with a stack trace or so?

In general we put the user id in the session and not the username, but Symfony calls it like that either way.

https://github.com/msgphp/msgphp/blob/cb4a10e00a5550e8f375573625ee9ae7337ba675/src/User/Infra/Security/SecurityUserProvider.php#L32-L56

Refreshing uses `find()`, not `findByUsername()`.

I can play with JWT bundle soonish. See also https://github.com/msgphp/symfony-demo-app/issues/10, thus if you get the basics working feel free to contribute it :)

**Comment by DevMDamien** [comment]
Hi,

The lexik/jwt-authentication-bundle call the function `loadUserByUsername()` after decoding the jwt.

in [LexikJWTAuthenticationBundle/Security/Guard/JWTTokenAuthenticator.php](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/18ccbc7c653a86efcee96c68ad772847ea06cb07/Security/Guard/JWTTokenAuthenticator.php)
```
    /**
     * Loads the user to authenticate.
     *
     * @param UserProviderInterface $userProvider An user provider
     * @param array                 $payload      The token payload
     * @param string                $identity     The key from which to retrieve the user "username"
     *
     * @return UserInterface
     */
    protected function loadUser(UserProviderInterface $userProvider, array $payload, $identity)
    {
        if ($userProvider instanceof UserProviderWithPayloadSupportsInterface) {
            return $userProvider->loadUserByUsernameAndPayload($identity, $payload);
        }
        return $userProvider->loadUserByUsername($identity);
    }
```

So if we put the user id rather than the username into the payload, the user can not be authenticated.

**Comment by ro0NL** [comment]
I think you should not rely on `UserInterface::getUsername()` to provide the payload, but instead the _actual username_ from the domain user (the entity object).

**Comment by DevMDamien** [comment]
When the jwt-authentication-bundle create the payload, it uses the `UserInterface::getUsername()` 

```
    /**
     * Add user identity to payload, username by default.
     * Override this if you need to identify it by another property.
     *
     * @param UserInterface $user
     * @param array         &$payload
     */
    protected function addUserIdentityToPayload(UserInterface $user, array &$payload)
    {
        $accessor                          = PropertyAccess::createPropertyAccessor();
        $payload[$this->userIdentityField] = $accessor->getValue($user, $this->userIdentityField);
    }
```

into [LexikJWTAuthenticationBundle/Services/JWTManager.php](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.4/Services/JWTManager.php)


So my solution is to add a `SecurityUser::getId()` to replace the actual `SecurityUser::getUsername()` and let the function `SecurityUser::isEqualTo()` works with the user id, and add the `SecurityUser::getUsername()` to return, in my case, the user email.

```
/**
 * @author Roland Franssen <franssen.roland@gmail.com>
 */
final class SecurityUser implements UserInterface, EquatableInterface, \Serializable
{
    private $id;
    private $username;
    private $roles;
    private $password;
    private $passwordSalt;

    public function __construct(User $user, array $roles = [])
    {
        $this->id = $user->getId()->toString();
        $this->username = $user->getCredential()->getUsername();
        $this->roles = $roles;

        $credential = $user->getCredential();
        if ($credential instanceof PasswordProtectedInterface) {
            $this->password = $credential->getPassword();

            $algorithm = $credential->getPasswordAlgorithm();
            if (null !== $algorithm->salt) {
                $this->passwordSalt = $algorithm->salt->token;
            }
        }
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function getUsername(): string
    {
        return $this->username ?? '';
    }

    public function isEqualTo(UserInterface $user)
    {
        return $user instanceof self && $this->id === $user->getId();
    }
```

Like you can see, it's just a workaround and it's working fine for me with my user email.

**Comment by ro0NL** [comment]
Looking at https://github.com/lexik/LexikJWTAuthenticationBundle/blob/460eda277ae9060d1b1bd8c015900a8111699376/Security/User/JWTUserProvider.php#L49 we create a specialized implementation perhaps? Could be shipped with `MsgPhp\IUser\Infra\Security\JWTPayloadFactory` or so?

Im not aware of any internals on JWT side really, if you can provide a reproducing app ill can have a look. But feel free to contribute anything that's needed.

**Comment by DevMDamien** [comment]
If we create an implementation, msgphp/user will have a dependency from lexik/jwt-authentication-bundle.

So the best solution is to develop another bundle to create the link between msgphp//user and lexik/jwt-authentication-bundle, isn't it?
