### ISSUE TITLE
No identifier/primary key specified for Entity "App\Entity\User\User" sub class of "MsgPhp\User\Entity\User"

### ISSUE THREAD

**Issue by dvc** [msgphp/msgphp#114]
"api-platform/api-pack": "^1.1",
By article: https://medium.com/@ro0NL/decoupling-the-user-entity-with-a-new-symfony-user-bundle-7d2d5d85bdf9

and (after errors with 'data_type_mapping') https://github.com/msgphp/msgphp/blob/master/UPGRADE-0.2.md

`composer req msgphp/user-bundle`

"msgphp/user-bundle": "^0.2.2",

```
# config/packages/msgphp_user.php

<?php

use App\Entity\User\User;
use MsgPhp\User\Entity\User as BaseUser;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return function (ContainerConfigurator $container) {
    $container->extension('msgphp_user', [
        'class_mapping' => [
            BaseUser::class => User::class,
        ],
    ]);
};
```

```
# src/Entity/User/User.php

<?php

namespace App\Entity\User;

use MsgPhp\User\Entity\User as BaseUser;
use MsgPhp\User\UserIdInterface;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity
 *
 * @final
 */
class User extends BaseUser
{
    private $id;

    public function __construct(UserIdInterface $id)
    {
        $this->id = $id;
    }

    public function getId(): UserIdInterface
    {
        return $this->id;
    }
}

```

```
$ bin/console d:s:c --dump-sql 
2018-03-15T13:32:52+00:00 [error] Error thrown while running command "'d:s:c' --dump-sql". Message: "No identifier/primary key specified for Entity "App\Entity\User\User" sub class of "MsgPhp\User\Entity\User". Every Entity must have an identifier/primary key."
```

ok, add annotation at $id

```
    /**
     * @var UserIdInterface
     * @ORM\Id()
     * @ORM\Column(type="uuid")
     */
    private $id;
```

it works

```
$ bin/console d:s:c --dump-sql 

 The following SQL statements will be executed:

     CREATE TABLE "user" (id UUID NOT NULL, PRIMARY KEY(id));
     COMMENT ON COLUMN "user".id IS '(DC2Type:uuid)';
```

but in documentation and blog posts it was enouth to add config for uuid (and zero configuration for integer.

```
        'id_type_mapping' => [
            UserIdInterface::class => 'uuid',
        ]

```

What is best practice for now?

**Comment by ro0NL** [comment]
Hi @dvc,

You're right, docs are incomplete and blog post is outdated regarding this.

Changing the entity identfiers was exactly what's 0.2 was about, see #87 for more info.

Basically today you have 2 options;

1)

```
@var UuidInterface
@ORM\Id()
@ORM\Column(type="uuid")

function getId(): UserInterface
{
    return MsgPhp\User\Infra\Uuid\UserId::fromValue($this->id);
}
```

You dont need to configure `id_type_mapping` as you already declared it as uuid, nevertheless it's good practice to keep it in sync, thus:

```
id_type_mapping:
   UserIdInterface: uuid // should match with type used in @Column
```

2)

```
@var UserIdInterface
@ORM\Id()
@ORM\Column(type="msgphp_user_id")

function getId(): UserIdInterface
{
    return $this->id;
}
```

In thise case you do need to configure `id_type_mapping`, as we dont know the type yet.

**Comment by ro0NL** [comment]
Basically this is about the difference in hydration of `$this->id`. Option 1 hydrates it as ramsey's `UuidInterface`, which you'll need to hydrate to a UserIdInterface at run-time (see getId()).

Option 2 hydrates as UserIdInterface directly.

**Comment by dvc** [comment]
@ro0NL, thank you for answer. Option 2 works for me. And looks clear.
