### ISSUE TITLE
Consider user groups/organizations/teams

### ISSUE THREAD

**Issue by ro0NL** [msgphp/msgphp#14]
This is currently a missing feature compared to FOSUserBundle.

Inspired by the whole github user-management flow, it could be nice to have something like;

- users can belong to one or more groups/teams
- users can belong to one or more organizations
- groups/teams can belong to one organization
- users might have a certain role within a group/team (owner / admin / member)
- users might have a certain role within an organization (owner / admin / member)
- `Group/Team` + `Organization` might share the same base entity to leverage a nested tree

**Comment by ssmusoke** [comment]
A Group/Team + Organization might have its own roles that are different from another, but each Group/Team can only access its own roles. 

This might also introduce the concept of pre-built roles which are used across organizations and teams but cannot be edited or changed only used as a starting point
