### ISSUE TITLE
Issue with @ORM\AssociationOverride

### ISSUE THREAD

**Issue by nottavi** [msgphp/msgphp#152]
` [Creation Error] The annotation @ORM\AssociationOverride declared on class App\Entity\User\UserRole does not have a property named "inversedBy". Available properties: name, joinColumns, joinTable `

is raised when I do php bin/console doctrine:schema:update --dump-sql (or --force) after I did create a User entity with doctrine maker as suggested in yout article on medium

According to a stackoverflow post inversedBy can be overridden since Doctrine 2.6 which I think is the version I've installed as I used composer req --dev orm annotations mgsphp/user-bundle ...

How could I solve this issue

Thanks,
Nicolas

**Comment by ro0NL** [comment]
Hi @nottavi 

Can you share `composer show` output? On our side we enforce ^2.6.. see https://github.com/msgphp/user-bundle/blob/master/composer.json#L28

**Comment by nottavi** [comment]
Hi as said on medium my composer show gives me : 
`doctrine/orm                        v2.5.14  Object-Relational-Mapper for PHP`

I do not really understand why

Thanks for your time. I'll look at it tomorrow or monday and let you know if I have something new.

**Comment by ro0NL** [comment]
Ah, sorry didnt compared timestamps :)

**Comment by nottavi** [comment]
Hi @ro0NL 
I did a simple brand new project to test again

When following these steps as mentioned in your article on Medium I still have v2.5.14 for doctrine/orm which explain the issue I raised.

```
composer create-project symfony/skeleton app/ && cd app/
composer require maker server --dev
composer require annotations form orm security simple-bus/symfony-bridge twig validator
composer show
```

It seems symfony/orm-pack requires the following according to its composer.json and [packagist](https://packagist.org/packages/symfony/orm-pack)
`"doctrine/orm": "^2.5.11"`

After doing
`composer req msgphp/user-bundle --dev` 
nothing changed concerning the version :(

For info:
`composer req msgphp/user-bundle --dev
Using version ^0.4.4 for msgphp/user-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Prefetching 3 packages 🎵
  - Downloading (100%)

Package operations: 3 installs, 0 updates, 0 removals
  - Installing msgphp/domain (v0.4.4): Loading from cache
  - Installing msgphp/user (v0.4.4): Loading from cache
  - Installing msgphp/user-bundle (v0.4.4): Loading from cache
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Symfony operations: 1 recipe (88f49d9c95524ad3ac7c9827c8740977)
  - Configuring msgphp/user-bundle (>=v0.4.4): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 230:
!!                                                                              
!!    The child node "class_mapping" at path "msgphp_user" must be configured.  
!!                                                                              
!!  
!!  
Script @auto-scripts was called via post-update-cmd`

**Comment by ro0NL** [comment]
Hi @nottavi 

`^2.5.11` should allow for 2.6.1, see https://semver.mwl.be/#?package=doctrine%2Form&version=%5E2.5.11&minimum-stability=stable

Maybe 2.6 is blocked on your machine due platform requirements? Perhaps see if `composer why-not doctrine/orm 2.6` shows a hint... 

For me it looks like:

```
$ composer why doctrine/orm
api-platform/api-pack  1.1.0   requires  doctrine/orm (^2.4.5)   
ramsey/uuid-doctrine   1.4.3   requires  doctrine/orm (^2.5)     
symfony/orm-pack       v1.0.5  requires  doctrine/orm (^2.5.11)  

$ composer show doctrine/orm
...
versions : * v2.6.1
```

About the receipe..im not sure yet what's happening. I expected `Configuring msgphp/user-bundle (>=v0.4.4): From auto-generated recipe` to use the [0.2 recipe](https://github.com/symfony/recipes-contrib/tree/master/msgphp/user-bundle/0.2), which would solve the error. Needs to be applied manually for now :)

**Comment by nottavi** [comment]
Finally got the correct version after doing a:

`composer update --dev
`

So pb solved I think
