### ISSUE TITLE
msgphp user with EasyAdmin

### ISSUE THREAD

**Issue by maxim2513** [msgphp/msgphp#156]
I installed EasyAdminBundle
 have problem with manage my users.
`The name "credential.email" contains illegal characters. Names should start with a letter, digit or underscore and only contain letters, digits, numbers, underscores ("_"), hyphens ("-") and colons `(":").`

`FormConfigBuilder::validateName('credential.email')`

could you help me?

**Comment by ro0NL** [comment]
Hi @maxim2513 

So far im having the same issues, see https://github.com/msgphp/symfony-demo-app/pull/45 :) and there are more also.

In  my experience Easyadmin is not really compatible with _any entity_ design, esp. embeddables from Doctrine pov. Not sure how to move forward, i believe some work needs to be done upstream first, see: https://github.com/EasyCorp/EasyAdminBundle/pull/2209 and https://github.com/EasyCorp/EasyAdminBundle/issues/2223

**Comment by ro0NL** [comment]
Related to forms.. i havent investigated if a workaround is possible.

**Comment by ro0NL** [comment]
@maxim2513 ive closed https://github.com/msgphp/symfony-demo-app/pull/45 and therefor i think we can close this one as such. Feel free to re-open if you think anything should change on msgphp side. For now i think the compat issue lives at Easyadmin.
