### ISSUE TITLE
User can can register but not login

### ISSUE THREAD

**Issue by mdimitris** [msgphp/msgphp#157]
Hello,
I followed this [guide ](https://medium.com/@ro0NL/adding-user-management-to-your-symfony-application-ceeefe2a2e9) and I installed msgphp/user in clean installation. However when I try to login it always the message "bad credentials" appears. Also, I dont know whether it is related but when a yuser is registered no entry is taking place in user_role table. Below the security.yaml exists:

```
security:
    encoders:
        MsgPhp\User\Infra\Security\SecurityUser: sha512
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }
        msgphp_user: { id: MsgPhp\User\Infra\Security\SecurityUserProvider }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: msgphp_user

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: /login
                check_path: /login
                default_target_path: /profile
                username_parameter: email
                password_parameter: password

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        #- { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: IS_AUTHENTICATED_FULLY }
```

**Comment by ro0NL** [comment]
hi @mdimitris 

can you share your user entity :) looks related to `sha512` which needs to be taken into account for in user credential as well.

Bcrypt is default compatible with `Email/NicknamePassword` credential due https://github.com/msgphp/msgphp/blob/078304a6a80797a5c8ebd8b9b2d53ddece228b15/src/User/Entity/Credential/Features/PasswordProtected.php#L22-L25

Whereas `sha512` is default compatible with `Email/NicknameSaltedPassword` credential due https://github.com/msgphp/msgphp/blob/078304a6a80797a5c8ebd8b9b2d53ddece228b15/src/User/Entity/Credential/Features/PasswordWithSaltProtected.php#L24-L27

> no entry is taking place in user_role table

correct, by default no database roles are inserted or so, this is up to you :)

**Comment by mdimitris** [comment]
hi @ro0NL and thanks for your fast reply! I am posting here the user entity from src/Entity/User/User.php. 

`
namespace App\Entity\User;

use Doctrine\ORM\Mapping as ORM;
use MsgPhp\User\Entity\User as BaseUser;
use MsgPhp\User\UserIdInterface;
use MsgPhp\Domain\Event\DomainEventHandlerInterface;
use MsgPhp\Domain\Event\DomainEventHandlerTrait;
use MsgPhp\User\Entity\Credential\EmailSaltedPassword;
use MsgPhp\User\Entity\Features\EmailSaltedPasswordCredential;
use MsgPhp\User\Entity\Features\ResettablePassword;
use MsgPhp\User\Entity\Fields\RolesField;

/**
 * @ORM\Entity()
 */
class User extends BaseUser implements DomainEventHandlerInterface
{
    use DomainEventHandlerTrait;
    use EmailSaltedPasswordCredential;
    use ResettablePassword;
    use RolesField;

    /** @ORM\Id() @ORM\GeneratedValue() @ORM\Column(type="msgphp_user_id") */
    private $id;

    public function __construct(UserIdInterface $id, string $email, string $password, string $passwordSalt = null)
    {
        $this->id = $id;
        $this->credential = new EmailSaltedPassword($email, $password, $passwordSalt);
    }

    public function getId(): UserIdInterface
    {
        return $this->id;
    }
}`

In case I want to change the user authentication from salted to normal and back how can I do it?

**Comment by ro0NL** [comment]
ill try to reproduce with sha512 tomorrow or so...

to switch back to bcrypt your user entity would look like:

```diff
-use EmailSaltedPasswordCredential;
+use EmailPasswordCredential;

-$this->credential = new EmailSaltedPassword($email, $password, $passwordSalt);
+$this->credential = new EmailPassword($email, $password, $passwordSalt);
```

**Comment by ro0NL** [comment]
@mdimitris im on this :) there a few missing steps still.

the trick is to provide the salt upfront during registration

**Comment by ro0NL** [comment]
@mdimitris also, is there any real reason to use `sha512`? It's doable, sure... (e.g. you need to specify the `password_algorithm` option on `HashedPasswordType` to get the correct password.

In general the user entity need to be constructed as follow:

```
$salt = 'random salt';
$algo = PasswordAlgorithm::createLegacySalted(new PasswordSalt($salt));
new User($email, $passwordHashing->hash('plain', $algo), $salt);
```

Thing is, im not sure to implement all this with `make:user`. Instead, im leaning to disable the salted password credentials here (given you should not really use this today and msgphp is a new project).

Raises the question: why are you using sha512? :)

**Comment by mdimitris** [comment]
#r0NL hi! Actually I don't have any requirement to use salt password. So in case I want to use the usual method how my user entity should be?  Should I make changes also in some controllers?

**Comment by ro0NL** [comment]
@mdimitris with self-salting passwords (e.g. bcrypt) no need to change controllers, etc. There's nothing to pass to e.g. form options, you just get the correct hashed value from the `HashedPasswordType`.

So most likely it looks something like: https://github.com/msgphp/symfony-demo-app/blob/master/src/Entity/User/User.php#L41
