### ISSUE TITLE
LexikJWTAuthenticationBundle rename interface 

### ISSUE THREAD

**Issue by dvc** [msgphp/msgphp#164]
https://github.com/lexik/LexikJWTAuthenticationBundle/commit/aa5ef989484333551d4aa68dbdbab213f60e9657

It is in all 2.5.* and master.

fast workaround:
```
composer require "lexik/jwt-authentication-bundle:dev-master#a3d590ec57cac3a0b4618a1d817ceb8eb6f9141a"

```

**Comment by ro0NL** [comment]
See #164
