### ISSUE TITLE
Roles pre-load not exists

### ISSUE THREAD

**Issue by carlofraue79** [msgphp/msgphp#172]
Hi,
it is possible to create the commands to create the roles or load the roles to working with symfony 4 and symfony/flex?
I haven't found any solution on it.
Can you help me ?

**Comment by ro0NL** [comment]
Hi @carlofraue79 

Im not sure i follow your question. Do you propose to add `Create/DeleteRoleCommands`? I think that makes sense, as `AddUserRoleCommand` won't cascade persist new role entities.

Hence the demo app creates the roles from a fixture: https://github.com/msgphp/symfony-demo-app/blob/22484ca051129340c0ff94e5f1d6479d649708ec/src/DataFixtures/ORM/Users.php#L34-L35

Are we actually talking about database roles? Or in-memory roles maybe? See https://github.com/msgphp/symfony-demo-app/blob/master/src/Security/UserRolesProvider.php

**Comment by carlofraue79** [comment]
@ro0NL Actually i'm excepted that the roles are already persists into the database in tables "roles" and i think that the  commands "php bin/console user:role:add" doesn't return the following error Username:
 > admin@admin.it

 Role name:
 > ROLE_ADMIN


**In EntityNotFoundException.php line 14:
                                                                                        
  Entity "App\Entity\User\Role" with identifier {"name":"ROLE_ADMIN"} cannot be found.**

**Comment by ro0NL** [comment]
Im not sure what's the better practice;

We could cascade persist new roles, but i tend to prefer to make it an explicit step. So the role needs to exists before you can add it to a user.

So in CLI it be:

```
bin/console role:create ROLE_ADMIN
bin/console user:role:add user@domain.dev ROLE_ADMIN
```

Would that work for you?

**Comment by ro0NL** [comment]
The `role:create` command doesnt exist, i suggested to add it.

So currently you need to create the role (manually in DB / using Doctrine fixtures) before you can add it to a user. You can only reference **existing** roles with `user:role:add`.
