### ISSUE TITLE
How to force dispatch to event_bus properly?

### ISSUE THREAD

**Issue by jkabat** [msgphp/msgphp#174]
I'm trying to use your msgphp/domain for custom commands and handling works fantastic. However I'd like to use possibility to dispatch unhandled events from commands to event_bus.

ATM I can do it only by creating msgphp.domain.events parameter and listing them all in there.
Is there any other more convenient way?

There is very little documentation for symfony messenger component... so most probably I'm missing some piece of puzzle. What I want to do is to use allow_no_handler middleware for event_bus (as msgphp/user is using).

**Comment by ro0NL** [comment]
Hi @jkabat ,

MsgPHP internally uses a `DomainMessageBusInterface` which knows about the (internal) commands and events. This allows us to use a single bus for both message types.

In general you're not required to use our `DomainMessageBusInterface` in your application. You can leverage the `@command_bus` and `@event_bus` where needed as usual.

So if you want to dispatch an event from your handler, the event bus should be injected.

See e.g. https://github.com/msgphp/symfony-demo-app/blob/master/src/Controller/User/RegisterController.php#L24 which just uses the SF messenger command bus. It's the same instance we wrapped into `DomainMessageBusInterface` internally.

Hope this clarifies.

**Comment by ro0NL** [comment]
Sure, that's what i'm doing here as well: https://github.com/msgphp/symfony-demo-app/blob/master/src/EventSubscriber/EnableConfirmedUser.php#L11
