### ISSUE TITLE
Factorize security user

### ISSUE THREAD

**Issue by ro0NL** [msgphp/msgphp#176]
Getting the `SecurityUser` from the user provider could use the factory (which it already has scope to).

https://github.com/msgphp/msgphp/blob/576d29f4ac902f7abc348669af8eaddfef108772/src/User/Infra/Security/SecurityUserProvider.php#L65-L68

That way the class being used can be overridden with a custom one using the `class_mapping` config.

As `SecurityUser` is final it only makes sense to provide our user interface as well, e.g.;

```
namespace Msgphp\User\Infra\Security;

interface UserInterface extends BaseUserInterface, EquatableInterface, \Serializable
{
}
```

or make it non-final :)

**Comment by trimpirim** [comment]
@ro0NL What is the status of this?

**Comment by ro0NL** [comment]
@trimpirim ill pick this one up tomorrow. Can you clarify your goal.. e.g. would extending our `SecurityUser` work for you? Or do you prefer a custom implementation, thus the interface.

**Comment by trimpirim** [comment]
Extending would work for me pretty well, I think. If you could manage to register that as a something so your final SecurityUserProvider would use my extended SecurityUser - that would be cool too. 
The problem I have is that I need to get the User behind the SecurityUser. I might have missed something, there might be another way to get the provided real User, but I can not find that, so I have to create my own SecurityUserProvider and my own SecurityUser just to get the real User.

Does it make sense?

**Comment by ro0NL** [comment]
@trimpirim hm not sure, you can get the "real user", aka the "domain user", aka the "user entity" by simply quering it. In general you dont want it to end up in the session (hence we dont use the entity for a securtity user).

`$entityUser = $userRepo->find(UserId::fromValue($securityUser->getUsername()))` something like that should do it.

To get the current user in a controller you can use the param converter, e.g.

https://github.com/msgphp/symfony-demo-app/blob/09fcc34b6b0abea031ca482bf0f9dd66c8601f2b/src/Controller/User/MyAccountController.php#L31-L35

**Comment by ro0NL** [comment]
@trimpirim so closing in favor of #186

the solution is to query your entity when needed.

But note there are default ways to do so: e.g. param converters). Otherwise, using the built-in `UserRepository`, in 0.6 this is made easier: `$user = $repo->find($securityUser->getUserId())`.

**Comment by ro0NL** [comment]
> Okey, I found out that you have twig extension that allows you to get the user, cool.

I was about to mention that :)

> what was your case?

non really :sweat_smile: just a technical possibility. Currently the provider has no scope to the factory anymore (because it's unneeded) so the original issue is defeated.
