### ISSUE TITLE
user table name conflicts with Postgres

### ISSUE THREAD

**Issue by TiFaBl** [msgphp/msgphp#177]
I included the awesome userbundle into a symfony project that uses a postgres db. When i tried `/register` or `bin/console user:create` it failed with SQL Errors at `user`.

> In AbstractPostgreSQLDriver.php line 80:
>                                                                                                                                                        
>   An exception occurred while executing 'SELECT u0_.password_reset_token AS password_reset_token_0 FROM user u0_ WHERE u0_.credential_email = 'test@local.com'':                                                                                                                                            
>                                                                                                                                                        
>   SQLSTATE[42703]: Undefined column: 7 ERROR:  column u0_.password_reset_token does not exist

I figured out that postgres refers to its own user table and therefore does not provide the required columns. Adjusting the table name for the user entity fixed the problem for me.

```
** Entity/User/User.php **
...
/**
 * @ORM\Entity()
 * @ORM\Table(name="appuser")
 */
class User extends BaseUser implements DomainEventHandlerInterface
...
```

**Comment by ro0NL** [comment]
Hey @TiFaBl 

Not sure what can be done on our side... conceptually it's related to #159, as it's caused by doctrine defaults. As you've shown, it's easy to workaround / customize (which is how this bundle is designed).

Suggestions welcome ;)
