### ISSUE TITLE
[Feature Request] Add isPasswordValid to User model with parameter of plaintext password to ease validation of plain text passwords

### ISSUE THREAD

**Issue by ssmusoke** [msgphp/msgphp#188]
This is usually common when changing passwords

**Comment by ro0NL** [comment]
https://github.com/msgphp/msgphp/blob/master/src/User/Password/PasswordHashingInterface.php#L14 ?

**Comment by ssmusoke** [comment]
@ro0NL Sorry had meant to specify the User model or credential interface (probably) - that way the implementation details are hidden from the user

**Comment by ro0NL** [comment]
but they're unaware of any service.. so this should be done where needed:

```
$passwordHashing->isValid($user->getCredential()->getPassword(), 'plain', $user->getCredential()->getPasswordAlgorithm())
```

Or use the built-in `HashedFormType` in a form context, e..g see https://github.com/msgphp/symfony-demo-app/blob/master/src/Form/User/ResetPasswordType.php#L12

**Comment by ssmusoke** [comment]
Got you - thank you for the clarification
