### ISSUE TITLE
Phpstan warning on subclassing DomainId

### ISSUE THREAD

**Issue by danaki** [msgphp/msgphp#206]
Not sure it's a bug, but can't find a way to get rid of it. In my code I have:
```
        $cc = new PaymentSystem();
        $cc->setId(PaymentSystemId::fromValue('sepa'));
```

Entity\PaymentSystem.php
```
...
    public function setId(PaymentSystemIdInterface $id)
    {
        $this->id = $id;
    }
...
```

where PaymentSystemId is:
```
<?php

namespace App\Entity\Id;

use MsgPhp\Domain\DomainId;

class PaymentSystemId extends DomainId implements PaymentSystemIdInterface
{
}
```

```
<?php

namespace App\Entity\Id;

use MsgPhp\Domain\DomainIdInterface;

interface PaymentSystemIdInterface extends DomainIdInterface
{
}
```

And phpstan complains:
```
[phpstan] Parameter #1 $id of method App\Entity\PaymentSystem::setId() expects App\Entity\Id\PaymentSystemIdInterface, MsgPhp\Domain\DomainId given.
```

Am I missing something?

**Comment by ro0NL** [comment]
HI @danaki i havent noticed this yet :) i can give it a try tomorrow.

Could be related to 

https://github.com/msgphp/msgphp/blob/d7db480c438fbd0648ed79b8e3a7f322bf597927/src/Domain/DomainId.php#L14-L17

Now looking at it, `self` is not the interface return type here, that's `DomainIdInterface`.  Can you try that?

**Comment by danaki** [comment]
If I understood you correct, I've changed 
```
final public static function fromValue($value): DomainIdInterface 
```
to 
```
final public static function fromValue($value): self
```

and now getting 
```
[phpstan] Declaration of MsgPhp\Domain\DomainId::fromValue($value): MsgPhp\Domain\DomainId must be compatible with MsgPhp\Domain\DomainIdInterface::fromValue($value): MsgPhp\Domain\DomainIdInterface in /Users/yuri/work/ex/bitwana/backend/vendor/msgphp/domain/DomainId.php on line 10
```

Well, that was my choice to go with anemic models because I was afraid Sonata Admin won't understand this approach. However then I found this recipe https://symfony.com/doc/master/bundles/SonataAdminBundle/cookbook/recipe_data_mapper.html however it doesn't work (may be something changed in Sonata since this recipe was written) :)

**Comment by ro0NL** [comment]
see #207 :)
