### ISSUE TITLE
Invalid field override named 'user' for class 'App\Entity\User\UserRole'.

### ISSUE THREAD

**Issue by vitalicwow** [msgphp/msgphp#209]
I'm trying to use the UserBundle, I've used the maker to create my entities and installed all dependencies, tried everything I can think of but this error has defeated me, any ideas what it could be? It's a shame as would like to use this project.

`In MappingException.php line 139:
!!
!!    Invalid field override named 'user' for class 'App\Entity\User\UserRole'.`

**Comment by ro0NL** [comment]
HI @vitalicwow , can you confirm `RolesField` was added to your `User` entity after running `make:user:msgphp`? I.e. https://github.com/msgphp/symfony-demo-app/blob/master/src/Entity/User/User.php#L34

If you removed it you need to remove the attribute override for UserRole as well, i.e. https://github.com/msgphp/symfony-demo-app/blob/master/src/Entity/User/UserRole.php#L11

**Comment by vitalicwow** [comment]
This was the entity that was created: https://gist.github.com/vitalicwow/1b8b8675004569957de3228f44b5f4ad

It did appear to have RolesField, I tried it without also. I also tried just copying the entity from the demo app, but no dice. I do need to have user roles so removing it altogether isn't an option.

**Comment by ro0NL** [comment]
@vitalicwow  i took the following steps

```
$ composer create-project symfony/skeleton test && cd test
$ composer require annot form validator twig security messenger orm
$ composer require maker server --dev
$ composer require msgphp/user-bundle
$ bin/console user:make:msgphp
```

Answered all by default and written the files.

```
bin/console doctrine:schema:validate --skip-sync

Mapping
-------

                                                                                                                        
 [OK] The mapping files are correct.                                                                                    
                                                                                                                        

Database
--------

 [SKIPPED] The database was not checked for synchronicity.
```

Are we on the same page so far?
