### ISSUE TITLE
Installing msgphp but getting errors

### ISSUE THREAD

**Issue by fragbait** [msgphp/msgphp#229]
Everything else for Symfony 4 has installed okay, but when I run....
 
bin/console make:user:msgphp

give me the following error

Enable Symfony Messenger configuration? (config/packages/messenger.yaml) (yes/no) [yes]:
 > 2018-11-10T02:32:50+00:00 [error] Error thrown while running command "make:user:msgphp". Message: "Warning: Use of undefined constant STDIN - assumed 'STDIN' (this will throw an Error in a future version of PHP)"

In QuestionHelper.php line 111:

  Warning: Use of undefined constant STDIN - assumed 'STDIN' (this will throw an Error in a future version of PHP)

make:user:msgphp [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

Content-type: text/html; charset=UTF-8

php -v
ea-php-cli Copyright 2017 cPanel, Inc.
PHP 7.2.11 (cgi-fcgi) (built: Nov  6 2018 20:23:02)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

Any ideas from anyone?

**Comment by ro0NL** [comment]
Hi @fragbait this seems related to your environment / PHP installation. Worst case it's a bug in Symfony though.

See https://3v4l.org/T0CBd

**Comment by ro0NL** [comment]
Yep, i suggest to open an issue at https://github.com/symfony/symfony

To report the broken usage of STDIN on windows in https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Helper/QuestionHelper.php#L111

I.e the fallback may be something like https://www.experts-exchange.com/questions/21388294/STDIN-under-Windows.html
