### ISSUE TITLE
error during schema update

### ISSUE THREAD

**Issue by mdimitris** [msgphp/msgphp#234]
Hello,

I try to update the schema of the database but  when I am running the command "bin/console doctrine:schema:update --force" I receive the following error:
![2018-11-23_1956](https://user-images.githubusercontent.com/13381153/48956185-45af1f80-ef5a-11e8-863d-12f151be7425.png)

I dont know whether it is relevant but I am using postgre and not mysql.

Thanks in advance

**Comment by ro0NL** [comment]
HI @mdimitris 

Could you share a reproducing app maybe? Otherwise some more info is needed (msgphp bundle config + related entity code).

**Comment by mdimitris** [comment]
Hello @ro0NL!
I paste below the entity code :

user.php

`<?php

namespace App\Entity\User;

use App\Entity\Application;
use App\Entity\DoctorData;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use MsgPhp\User\Entity\User as BaseUser;
use MsgPhp\User\UserIdInterface;
use MsgPhp\Domain\Event\DomainEventHandlerInterface;
use MsgPhp\Domain\Event\DomainEventHandlerTrait;

use MsgPhp\User\Entity\Credential\EmailSaltedPassword;
use MsgPhp\User\Entity\Features\EmailSaltedPasswordCredential;

use MsgPhp\User\Entity\Credential\EmailPassword;
use MsgPhp\User\Entity\Features\EmailPasswordCredential;


use MsgPhp\User\Entity\Features\ResettablePassword;
use MsgPhp\User\Entity\Fields\RolesField;

/**
 * @ORM\Entity()
 */
class User extends BaseUser implements DomainEventHandlerInterface
{
    use DomainEventHandlerTrait;
    use EmailPasswordCredential;
    use ResettablePassword;
    use RolesField;

    /** @ORM\Id() @ORM\GeneratedValue() @ORM\Column(type="msgphp_user_id") */
    private $id;


    
    public function __construct(UserIdInterface $id, string $email, string $password)
    {
        $this->id = $id;
        $this->credential = new EmailPassword($email, $password);
    }

    public function getId(): UserIdInterface
    {
        return $this->id;
    }

 
    public function __toString(){
        return  strval($this->id);
    }
}`

`<?php

declare(strict_types=1);

namespace App\Entity\User;

use Doctrine\ORM\Mapping as ORM;
use MsgPhp\User\Entity\Role as BaseRole;

/**
 * @ORM\Entity()
 *
 * @final
 */
class Role extends BaseRole
{
    /** @ORM\Id() @ORM\Column() */
    private $name;

    public function __construct(string $name)
    {
        $this->name = $name;
    }

    public function getName(): string
    {
        return $this->name;
    }
}`

`<?php

declare(strict_types=1);

namespace App\Entity\User;

use Doctrine\ORM\Mapping as ORM;
use MsgPhp\User\Entity\UserRole as BaseUserRole;

/**
 * @ORM\Entity()
 * @ORM\AssociationOverrides({
 *     @ORM\AssociationOverride(name="user", inversedBy="roles")
 * })
 *
 * @final
 */
class UserRole extends BaseUserRole
{
}`


config/packages/msgphp_user.php
`<?php

use MsgPhp\User\Entity\User;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return function (ContainerConfigurator $container) {
    $container->extension('msgphp_user', [
        'class_mapping' => [
            User::class => \App\Entity\User\User::class,
        ],
    ]);
};`

**Comment by ro0NL** [comment]
@mdimitris you need to map all entity classes in order to activate them.

```php
User::class => \App\Entity\User\User::class,
Role::class => \App\Entity\User\Role::class,
UserRole::class => \App\Entity\User\UserRole::class,
```

**Comment by mdimitris** [comment]
@ro0NL I added them as instructed and now I am receiving the following:

> In Class MappingNode.php line 33: 
> A class or interface named "Role" does not exist at path "msgphp_user.class_mapping"

The class however exists in app\entity\user... I m totaly lost...

**Comment by mdimitris** [comment]
Ok it was rather simple.. I had to add also

```
use MsgPhp\User\Entity\User;
use MsgPhp\User\Entity\Role;
use MsgPhp\User\Entity\UserRole;
```

In the msgphp_user.php. Thanks for the help!

**Comment by ro0NL** [comment]
Cool :)
