### ISSUE TITLE
Symfony 4.2: invalid messenger config in skeleton

### ISSUE THREAD

**Issue by crabnky** [msgphp/msgphp#237]
I updated Symfony to 4.2 version and getting `Invalid middleware: service "allow_no_handler" not found.` error when trying to clear the cache.
Did I miss something?

Thanks.

**Comment by ro0NL** [comment]
Yep :) see https://github.com/msgphp/symfony-demo-app/pull/65 which updates the demo app to 4.2, but im working on it still (testing really)... but i need some more time.

In general your errror is related to changes in Symfony Messenger actually, i've updated it here:

https://github.com/msgphp/symfony-demo-app/pull/65/files#diff-ac4c9a179f396cd24ffc52ea04c5afe2

**Comment by ro0NL** [comment]
Ha! i should also update the skeleton file for the next release:

https://github.com/msgphp/msgphp/blob/master/src/UserBundle/Resources/skeleton/messenger.php

**Comment by ro0NL** [comment]
fixed in https://github.com/msgphp/msgphp/commit/db93d2e74825051f4d6c82e84d1d6b55331180ac

**Comment by mdimitris** [comment]
Hello! I am facing the same problem exactly..Because I am (very) novice to symfony and git usage could you please write me how I should use the git commands in order to be able to update it in a symfony installation?

**Comment by ro0NL** [comment]
hi @mdimitris i need to do some research still, im unaware of upstream changes. I'll check if everything is ok together with #377 though.
