### ISSUE TITLE
No handler for message "MsgPhp\User\Event\UserCreatedEvent".

### ISSUE THREAD

**Issue by dedioweb** [msgphp/msgphp#263]
Hello
I just followed the process on https://medium.com/@ro0NL/adding-user-management-to-your-symfony-application-ceeefe2a2e9

When I go to the / register page, after submission, I get this error: No handler for message "MsgPhp\User\Event\UserCreatedEvent".

TraceableMessageBus->dispatch(object(CreateUserCommand))
in src/Controller/User/RegisterController.php (line 34)

`): Response {        $form = $formFactory->createNamed('', RegisterType::class);        $form->handleRequest($request);        if ($form->isSubmitted() && $form->isValid()) {            $bus->dispatch(new CreateUserCommand($form->getData()));            $flashBag->add('success', 'You\'re successfully registered.');            return new RedirectResponse('/login');        }`

I do not see how to fix that?
In advance, thank you and sorry for my english, I'm french :-)

**Comment by ro0NL** [comment]
Hi @dedioweb i think you need to setup a event bus still, see https://msgphp.github.io/docs/cookbook/configuring-symfony-messenger/#configure-a-command-and-event-bus

for event buses the `default_middleware: allow_no_handlers` is key :)

**Comment by dedioweb** [comment]
Hello
thank you indeed, it works, for cons I do not see the message ('You\'re successfully registered.') appear on the redirect page (/ login) after registration

**Comment by ro0NL** [comment]
@dedioweb maybe you need to render flashes still in your template, here's how did in the demo app:

https://github.com/msgphp/symfony-demo-app/blob/master/templates/base.html.twig#L35 + https://github.com/msgphp/symfony-demo-app/blob/master/templates/partials/flashes.html.twig

to verify you can check the webprofiler, to see if the flash messages are put in the session. Then for sure it's missing rendering :)

**Comment by dedioweb** [comment]
@ro0NL 
it's fixed now :-)
