### ISSUE TITLE
Stable version bundle

### ISSUE THREAD

**Issue by MvanRietschoten** [msgphp/msgphp#28]
Hello,

Could you please create a v1.0.0 or 1.0.0 tag on the bundle(https://github.com/msgphp/user-bundle)?
That way, we can use a stable release in our composer.json.

I like myself some stable dependencies 👍

**Comment by GawainLynch** [comment]
It is coming … there are some things to be done first, but the :hamster: :hamster: are working hard behind the scenes to make it happen!

**Comment by MvanRietschoten** [comment]
Ah ok awesome. v0.1.0 would be nice indeed 👍 

I am using this bundle as it is a symfony contrib recipe.
It is a lot of classes you have to add manually.
I would suggest clearing up the docs / expanding the docs first for v1.0.0 indeed :)
The demo bundle is good enough documentation for now though ;) https://github.com/msgphp/symfony-demo-app

Keep up the good work 😃

**Comment by ro0NL** [comment]
> It is a lot of classes you have to add manually.

I assume you refer to _your_ entities the `App\Entity` namespace? That's the point :) you want to own these objects. If you want to use the core objects directly (with e.g. doctrine) you need to map those as entities yourself (as core only provides mapped super class mappings).
