### ISSUE TITLE
Cannot autowire service "MsgPhp\Domain\Infra\ApiPlatform\ProjectionDataProvider"

### ISSUE THREAD

**Issue by marcinj1** [msgphp/msgphp#292]
Hello, after installing integration with API bundle i'm getting
 ```
Cannot autowire service "MsgPhp\Domain\Infra\ApiPlatform\ProjectionDataProvider": argument "$typeRegistry" of method "__construct()" references interface "MsgPhp\Domain\Projection\ProjectionTypeRegistryInterface" but no such service exists. Did you create a cl  
  ass that implements this interface?     
```

I'm not able also to find bin/console projection:initialize-types

**Comment by ro0NL** [comment]
Hi @marcinj1, the domain projection model is still a concept phase :) there's no bundle or so what configures the services/infrastructure for you. And i might revamp some architecture parts: #199, #238

The manual wiring can be found in the demo app for now: https://github.com/msgphp/symfony-demo-app/blob/master/config/packages/api_projections.yaml

Let me know if it works :) or feel free to join Symfony Slack. If anything a `composer show msgphp/*` always helps.

**Comment by ro0NL** [comment]
Feel free to re-open :)
