### ISSUE TITLE
Investigate binary UUID

### ISSUE THREAD

**Issue by ro0NL** [msgphp/msgphp#3]
https://github.com/spatie/uuid-mysql-performance

`UserId::toBinary` + specialized doctrine type? configurable?

**Comment by kejwmen** [comment]
`DomainId` could be renamed to `UUID` or `DomainUUID` - this is UUID-specific `DomainIdInterface` implementation, so it would bo good to explicitly tell that.

Separate doctrine type :+1: 

`UserId::toBinary` + `UserId::fromBinary` sounds good

> configurable

note in the docs telling you can override column definition with example for binary uuid? 

Can I implement this one?

**Comment by ro0NL** [comment]
Im revamping domain ids in #25, will push a commit tomorrow that refactors a few things by design. Focusing on auto increment support first :) the infra will indeed be redesigned to support various type implementations, thus binary UUID is next :)

**Comment by kejwmen** [comment]
:ok_hand:, ping me if I can help anyhow.

**Comment by ro0NL** [comment]
@kejwmen first steps are done in #25, for now i added a new type in tests: https://github.com/msgphp/msgphp/pull/25/files#diff-453d06ec57117ecdd72924b59b3cdb8dR564

Ill finish that PR asap. But it's a bit more work as im setting up a abstract repository testing framework (so `InMemory` implem and eventually future implems are tested the same way. Once that's OK and we have first class citizen domain ids, so we can focus on their doctrine types.

In general, design-wise, i was hoping to settle with 1 type only, thus `Doctrine\DomainIdType`. Which we construct with a certain implem, i.e. integer, uuid, binary uuid. To avoid doctrine types per implem.

If we have a single doctrine type, next the step is to update the bundles. To have `integer` implem by default (no more require ramsey/uuid dependency). Based on the class mapping of `UserIdInterface` we can pick a default implem for the type.

Thoughts?

**Comment by ro0NL** [comment]
> DomainId could be renamed to UUID or DomainUUID

I guess in general you'd use one type `DomainId` across your app (though multiple is possible). To have predictable naming i settled with `Infra\<Vendor>\DomainId`, thus `Infra\Uuid\DomainId`.

When using both types you could i.e.

```
use MsgPhp\Domain\DomainId;
use MsgPhp\Domain\Infra\DomainId as DomanUuid;
```

I tend to like that =/

**Comment by ro0NL** [comment]
Also to adhere to `User::getId(): UserIdInterface` contract we need multiple `UserId` implems.
