### ISSUE TITLE
Improve username wiring

### ISSUE THREAD

**Issue by ro0NL** [msgphp/msgphp#312]
If the `Username` entity is enabled:

```php
User\Username::class => \App\Entity\User\Username::class
```
but no `username_lookup` is configured, then  crash occurs:

```
Cannot autowire service "MsgPhp\User\Infrastructure\Doctrine\Repository\UsernameRepository": argument "$lookup" of method "__construct()" references class "MsgPhp\User\Infrastructure\Doctrine\UsernameLookup" but no such service exists.
```

Either forbid mapping the `Username` entity if no lookup is provided, or fix the wiring but keep a working username entity.

**Comment by crabnky** [comment]
Hey @ro0NL,
I can see this error and I have `username_lookup` defined... do I miss something?
Here is my msgphp_user.php:
```
use App\Entity\User\UserLoginName;
use MsgPhp\User\User;
use MsgPhp\User\UserEmail;
use MsgPhp\User\Username;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;

return function (ContainerConfigurator $container) {
    $container->extension('msgphp_user', [
        'class_mapping' => [
            User::class => \App\Entity\User\User::class,
            UserEmail::class => \App\Entity\User\UserEmail::class,
            Username::class => UserLoginName::class
        ],
        'default_id_type' => 'integer',
        'username_lookup' => [
            ['target' => UserEmail::class, 'field' => 'email', 'mapped_by' => 'user'],
        ],
        'doctrine' => [
            'auto_sync_username' => false
        ]
    ]);
};
```

**Comment by ro0NL** [comment]
Hi @crabnky it's still in dev-master only, im working the 0.11 release this weekend.

**Comment by crabnky** [comment]
Hey again @ro0NL ,

just updated  MgsPHP to version 0.13 (from 0.8) and I this error is still present...

**Comment by ro0NL** [comment]
Hi @crabnky, i think i understand. Can you confirm https://github.com/msgphp/msgphp/commit/de2a1562593a26f029911c4a4d58d35301a82056 solves it?

**Comment by crabnky** [comment]
Yeah, seems like this is solved. Have other issues (getId() of user entity returns integer istead of UserId, fromValue does not work anymore, have to look at this), but the autowire error is gone. Thanks! You are super fast! :))
