### ISSUE TITLE
User class implements undefined DomainEventHandlerInterface

### ISSUE THREAD

**Issue by tacman** [msgphp/msgphp#326]
The User class generated is 

    class User extends BaseUser implements DomainEventHandlerInterface

but that doesn't exist.  This works, but seems like is _should_ be an Interface:

    class User extends BaseUser implements DomainEventHandler

Similarly, RegisterController is calling CreateUserCommand, should be CreateUser

```php
        if ($form->isSubmitted() && $form->isValid()) {
            $bus->dispatch(new CreateUser($form->getData()));
```

**Comment by tacman** [comment]
Hmm, I went to create a PR and the changes were already in.

I think https://github.com/msgphp/user-bundle is out of date.

**Comment by ro0NL** [comment]
Hi @tacman 

I removed all type suffixes between v0.9 and v0.10; respectively https://github.com/msgphp/msgphp/tree/v0.9.1/src/User/Command vs. https://github.com/msgphp/msgphp/tree/v0.10.0/src/User/Command

So this looks like you used user-bundle@0.9 upon generating. It's safe to update to 0.10 and change these types in your app.

All code is hosted here in `msgphp/msgphp`. E.g. https://github.com/msgphp/user-bundle is a subtree split of https://github.com/msgphp/msgphp/tree/master/src/UserBundle

**Comment by tacman** [comment]
I was following the instructions at https://msgphp.github.io/docs/cookbook/user-bundle/installation/ and https://medium.com/@ro0NL/adding-user-management-to-your-symfony-application-ceeefe2a2e9 and 

When i look at composer.json, though, it is showing 0.10.  I did the entire process on another project, and the same thing happened.

**Comment by ro0NL** [comment]
Hi @tacman 

My bad, i figured i forgot to update the skeleton template files in 0.10 :(
https://github.com/msgphp/msgphp/blob/82899c2ae3688230719ca7ebbda1112b4ea176b2/src/UserBundle/Resources/skeleton/controller/RegisterController.php#L46

I fixed it in current master (upcoming v0.11): https://github.com/msgphp/msgphp/blob/2e93bf0671247c0fe68a4d12d6a073dabeb1cfb9/src/UserBundle/Resources/skeleton/controller/RegisterController.tpl.php#L34 But this is not released yet, i'll do that ASAP.

For now you can modify the wrongly generated code as needed.

**Comment by tacman** [comment]
What's the timetable on a fix for this?  I'm trying to port some apps from FOSUserBundle, and this keeps popping up.

**Comment by ro0NL** [comment]
@tacman im aim for it this friday/weekend :+1: (dev-master is the answer for now)
