### ISSUE TITLE
[bug] processClassFields fail on doctrine:mapping:import

### ISSUE THREAD

**Issue by ludovig** [msgphp/msgphp#331]
Using msgphp as a dependency for user support by user-bundle in a project, where not all my database tables where associated with doctrine entities, I got an error whenever I run : 

    php bin/console doctrine:mapping:import
or 
    php bin/console make:entity --regenerate 

I need to bypass processClassFields in domain/Infrastructure/Doctrine/Event/ObjectMappingListener or I get this error : Call to a member function getName() on null 

Thanks

**Comment by ro0NL** [comment]
Hi @ludovig 

I think we need to anticipate for null coming from getReflectionClass, yet contracts tell we don't have to:

https://github.com/doctrine/common/blob/df88fc88463a60f228a8233acf3fa8664897229c/lib/Doctrine/Common/Persistence/Mapping/ClassMetadata.php#L51

Can you confirm it's actually null in your case, and if bypassed as such ... does it solve the issue properly?

if not, can you share `composer show`

**Comment by ludovig** [comment]
Yes, I can confirm that an 
```php
if (null === $class) {
    return;
}
```
in the method, actually solved the issue…

**Comment by ro0NL** [comment]
Should be good then in `dev-master`. I'll release ASAP.
