### ISSUE TITLE
Allow ElasticSearch 6

### ISSUE THREAD

**Issue by tacman** [msgphp/msgphp#348]
In composer.json, only ElasticSearch 7 is allowed

```json
        "elasticsearch/elasticsearch": "^7.1",
```

But FOSElasticBundle is locked at version 6.  In order to avoid conflicts (and seriously, I don't even know if this is correct) could 6 be allowed, e.g.

        "elasticsearch/elasticsearch": "^6|^7.1",

I WISH FosElasticSearch and the underlying library supported 7, but it (literally, in the old fashion sense of the word, meaning literally) another issue.

**Comment by ro0NL** [comment]
i dont see any reason to disallow v6 actually (https://github.com/elastic/elasticsearch-php/blob/master/BREAKING_CHANGES.md#70)

both client versions work with both server versions, i guess

**Comment by ro0NL** [comment]
wait, which `composer.json` do you mean? The root composer.json is not a public package (only used for CI), so it cant be blocking

https://github.com/msgphp/msgphp/blob/master/composer.json#L7

eventually it will be put in require-dev at https://github.com/msgphp/domain/blob/master/composer.json, once tests are added :)

**Comment by ro0NL** [comment]
i thinks it's all good :)
