### ISSUE TITLE
Performance / Code style topics

### ISSUE THREAD

**Issue by ro0NL** [msgphp/msgphp#35]
Collected here so we can apply per topic and across te codebase at once, favoring consistency.

Topic | Current | Proposed
--- | --- | ---
~~root namespace~~ | `count($x)` | `\count($x)` :heavy_check_mark: 
~~class referecing~~ | `get_class($o)`, `get_called_class()` & co. | `self/static::class` :heavy_check_mark: 
~~string interpolation~~ | `sprintf('"%s"', $s)` | `'"'.$s.'"'` :heavy_check_mark: 
~~variable interpolation~~ [2]  | `"${var}"` :heavy_check_mark:  | `"{$var}"` :heavy_check_mark: 
~~array injection~~ [1] | inject by value | inject by parameter :heavy_check_mark: 
~~argument null-ability~~  | `string $x = null` | `?string $x = null` :heavy_check_mark: 

1) not sure if it affects perf really, reusing a param reduces dumped container though. Using params also exposes unwanted values, so ideally this is handled at the DI php dumper level.

2) https://secure.php.net/manual/en/language.types.string.php#language.types.string.parsing php-cs-fixer by default favors simple case.

**Comment by GawainLynch** [comment]
root namespace: :+1: 
string interpolation: I am torn on this one. While it is a _valid_ micro-op, IMHO it quickly makes code harder to read/follow. But that is just my €0.02

**Comment by iltar** [comment]
Often enough it's easy to inline or concat. When you really need formatting, sprintf is superior
