### ISSUE TITLE
'name' in UserRole missing

### ISSUE THREAD

**Issue by tacman** [msgphp/msgphp#351]
When configuring user-bundle, I selected "Nickname and Password", and now I'm getting an error when trying to update the database schema:
                                                                                                               
    Column name `name` referenced for relation from
    App\Entity\UserRole towards MsgPhp\User\Role does not exist.  

I did not get this error when choosing EmailAndPassword in the configuration.

**Comment by ro0NL** [comment]
interesting :) i expected a relation towards `App\Entity\Role` which holds the entity ID (`name` in this case).

Can you share your config?

**Comment by tacman** [comment]
Hmm, I can't recreate it now, so perhaps it was something else.  I've
installed / configured the bundle a few dozen times today, wishing very
much there was a --no-interaction that simply created everything.  Maybe
the credential type question could be configured on the command line?  So
that


    bin/console make:user:msgphp --credential-type=NicknamePassword
--no-interaction

Would simply create everything in one step.

Another idea: if there are no files to be overwritten, only new files
created, can you default the "show diff" to no?  In fact, I'd be fine if it
were always no.  Otherwise, the configuration is 30-some steps, almost all
of which are simply hitting return.

I'm working on a tutorial on how to "bootstrap" and deploy a Symfony4
application, and am using this bundle for security.

**Comment by ro0NL** [comment]
let's close then in favor of #353 for now :)

im very happy you testing the bundle, thanks :+1: feel free to share your tutorial once finished. Perhaps we can share it in Symfony weekly as well, let me know.
