### ISSUE TITLE
Write files even if no-interaction option is set

### ISSUE THREAD

**Issue by tacman** [msgphp/msgphp#352]
It'd be nice to generate all the defaults if --no-interaction is sent to the bin/console make:user:msgphp command

    bin/console make:user:msgphp --no-interaction

**Comment by ro0NL** [comment]
right, with `--no-interaction` the files should be written. That's not the case i assume? :sweat_smile:

**Comment by tacman** [comment]
It gets stuck in the confirmation loop, since the default is 'r'.

So either the default could change if no-interaction, or the loop
condition.
