### ISSUE TITLE
PostgreSQL & Doctrine & Symfony 4.3 SQL Querry BUG "user" Entity

### ISSUE THREAD

**Issue by RELAXccc** [msgphp/msgphp#354]
Sorry I don't often report bugs, but this is pretty simple to understand:

If you use PostgreSQL you cant make a query with SELECT * from user... because of
"user". It needs quotes in PostgreSQL.
If you make a migration Doctrine knows this, but some code in this bundle, or some of the auto-generated one (idk) does not do this, probably because it's not needed for MySQL. 

I think every DB would take this with "user", maybe it's a simple fix

**Comment by ro0NL** [comment]
Hi @RELAXccc do you have some hint where in the code this happens? in general we use Doctrine DQL / its entity manager ... so perhaps it's a bug upstream.

**Comment by RELAXccc** [comment]
![bug](https://user-images.githubusercontent.com/20889998/62371829-195e9080-b536-11e9-851f-794aac97d094.png)

sorry, I fixed it hours ago with renaming my User Entity. I only kept this screenshot. This was the error I had when I tried to use the (Default/Generated by your script) register form

**Comment by ro0NL** [comment]
this error seems to hint about a missing column :thinking: 

basically i need a stacktrace :) if this happens during registration the faulty query might be triggered by `UniqueUsernameValidator`, which ultimately uses https://github.com/msgphp/msgphp/blob/55e8d09f99f79fad5862f3a05efb2131e05ede56/src/Domain/Infrastructure/Doctrine/DomainEntityRepositoryTrait.php#L186

**Comment by RELAXccc** [comment]
sorry i don't have a stacktrace.
I fixed this by Renaming the "User" Entity to "Person" and replaced all  
use App\Entity\User;
with
use App\Entity\Person as User;

I guess its enough to just hint in the readme of the UserBundle that this happens with PostgreSQL and the "php bin/console make:user:msgphp" script

**Comment by ro0NL** [comment]
ok, i think i recall something where doctrine expects reserved keywords to be quoted in userland

can you specify the quoted table name using an annotation? see e.g. https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html#quoting-reserved-words

**Comment by ro0NL** [comment]
closing as explained. not sure it needs msgphp specific configuration. Nevertheless if you like to improve docs with a note based on your experience with Postgres feel free to do so :)

**Comment by RELAXccc** [comment]
I'm currently on vacation, when I'm back I will try to reproduce this to get a stacktrace.

I just assumed this may be a manual query of yours because I didn't find anyone else having this problem. Well, maybe it's just Symfony 4.3 , or some other combination. 

Thank you, I will Edit t he docs when I'm back. I'm really interested in getting this package better documented and working better out of the box.
