### ISSUE TITLE
Document creating a user with email and password

### ISSUE THREAD

**Issue by tacman** [msgphp/msgphp#362]
I'm trying to load some users programmatically, and am stuck.

https://msgphp.github.io/docs/cookbook/user-bundle/creating-a-user/

```php
/** @var MessageBusInterface $bus */
$bus->dispatch(new CreateUser([
    'id' => new ScalarUserId(),
    'email' => 'test@example.com',
   'password' => 'password'
]));
```

While the above creates a user, it's not correct.  What is the proper way to create a user with a password?  Can you also provide an example of creating ROLE_ADMIN and a user with that role?  

Thanks.  I've been trying to walk through the code, and I don't understand the contextDefinition and how the many classes, traits and interfaces related to each other.

**Comment by ro0NL** [comment]
Hey @tacman, see also #115. Im planning to document this with _Working with the user credential_ and _Working with user passwords_ :)

when creating the user, a hashed password should be given (assuming you're passing a plain password currently). When working with forms you can get a hashed password using the [`HashedPasswordType`](https://github.com/msgphp/msgphp/blob/master/src/User/Infrastructure/Form/Type/HashedPasswordType.php), or manually using the encoder directly, see e.g. https://github.com/msgphp/symfony-demo-app/blob/master/src/DataFixtures/AppFixtures.php#L93

> Can you also provide an example of creating ROLE_ADMIN and a user with that role?

something like

```php
$bus->dispatch(new CreateRole(['name' => 'ROLE_ADMIN']));
$bus->dispatch(new AddUserRole($userId, 'ROLE_ADMIN'));
```

**Comment by tacman** [comment]
Thanks.  On a related note, but probably okay to belong to this issue, how do I get a User record of type App\Entity\User?  Normally in twig I use "app.user", but this only gets me a UserIdentity.  I'm guessing I need to dispatch a message on the bus that fetches the user record, which will then include my custom fields, yes?  

Or I guess I can look it up via the UserRepository, e.g.

```php
        /** @var User $user */
        if (!$user = $this->userRepository->findByUsername($username = 'tt@example.com')) {
            throw new \Exception("$username not found.");
        }
```

Thanks.

**Comment by ro0NL** [comment]
in twig there's the `msgphp_user` variable for this purpose, see https://github.com/msgphp/symfony-demo-app/blob/master/templates/user/profile.html.twig#L3 :)

> I'm guessing I need to dispatch a message on the bus that fetches the user record, which will then include my custom fields, yes?

yes and no. There'a a concept called a "query bus" that could serve this purpose, however personally im in the "just use the repository" camp :) so yes using our `UserRepository` service is fine, or using Doctrine's EM directly.

To get the "current user" in the backend you may also use a ParamConverter annotation, see e.g. https://github.com/msgphp/symfony-demo-app/blob/e4c7981097bc93fdff29eb231a66b19503cbec69/src/Controller/ProfileController.php#L35-L38

Taking any of this routes is fine :) personally i aim to take the shortest one.

**Comment by tacman** [comment]
When I add dump(msgphp_user) to a twig template, I get

![image](https://user-images.githubusercontent.com/619585/63655174-f8631700-c752-11e9-8908-b7db68681ffb.png)

How do I access the fields of my user variable?

**Comment by tacman** [comment]
I see, {{ msgphp_user.current }} gets me the current user entity. Thanks.
