### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by abunch** [msgphp/msgphp#364]
Are there any plans to implement translations?

**Comment by ro0NL** [comment]
hi @abunch , can you clarify what should be translatable?

**Comment by abunch** [comment]
Anything where there's a pre-defined text string - I have a client that does a lot of work in Spanish speaking countries so it would be nice to have translations implemented.  Probably a low priority though.

**Comment by ro0NL** [comment]
:+1: for generating the skeleton controllers with translations, assuming you're hinting about the generated flash messages etc. I believe we need to generate a default translation file as well, to avoid "missing translations" warnings in the profiler.

Would you also expect CLI output to be translatable?

**Comment by abunch** [comment]
The CLI would be nice-to-have but the external facing stuff would be more important.

**Comment by ro0NL** [comment]
See #366 , i left CLI untouched. IMHO it's not common to do this in Symfony apps anyway.

Cheers, and happy translating :)
