### ISSUE TITLE
Invalid handler service "MsgPhp\User\Command\Handler\AddUserRoleHandler"

### ISSUE THREAD

**Issue by truckee** [msgphp/msgphp#369]
In a (relatively) new Symfony 4.3 project an attempt to integrate `msgphp/msgphp v0.13.0` resulted in the error `Invalid handler service "MsgPhp\User\Command\Handler\AddUserRoleHandler"`.  The installation sequence was

````
composer require simple-bus/symfony-bridge
composer require msgphp/user-bundle
compose require --dev sebastian/diff
composer require messenger
````
All files but `base.html.twig` were created and accepted as written when the command `make:user:msgphp` was run.

On loading the site the following exception & stack trace occurred:

Edit: This behavior occurs after configuring Symfony Messenger per the [docs](https://msgphp.github.io/docs/cookbook/configuring-symfony-messenger/)

````
RuntimeException 
Invalid  handler service "MsgPhp\User\Command\Handler\AddUserRoleHandler": bus  "simple_bus.command_bus" specified on the tag  "messenger.message_handler" does not exist (known ones are: event_bus).
--
in MessengerPass.php line 79
at MessengerPass->registerHandlers(object(ContainerBuilder), array('event_bus'))in MessengerPass.php line 68
at MessengerPass->process(object(ContainerBuilder))in Compiler.php line 94
at Compiler->compile(object(ContainerBuilder))in ContainerBuilder.php line 754
at ContainerBuilder->compile()in Kernel.php line 551
at Kernel->initializeContainer()in Kernel.php line 133
at Kernel->boot()in Kernel.php line 193
at Kernel->handle(object(Request))in index.php line 25
````

**Comment by ro0NL** [comment]
hi @truckee sorry for the late response

i need to figure out what currently happens when `simple-bus/symfony-bridge` is still installed, as i removed support in favor of Symfony messenger some time ago.

**Comment by ro0NL** [comment]
@truckee i reproduced it locally, and i think i understand what happens.

When configuring Symfony Messenger using

```
        buses:
            command_bus: ~
```

it creates a service `command_bus` for you to use, and you tell msgphp to use it via `msgphp.messenger.command_bus: '@command_bus'`

when installing `simple-bus/symfony-bridge` and enabling the `SimpleBusCommandBusBundle` bundle, this seems to overwrite the `command_bus` service (and so we hit the fan).

Im not sure how to resolve/detect the conflict. I suggest one of the following
- remove SimpleBusCommandBusBundle
- rename `command_bus` in `messenger.yaml`
- specify different command bus service ID in SimpleBusCommandBusBundle: https://github.com/SimpleBus/SymfonyBridge/blob/55d85e5c6ee55ba0c2dd4219c813673dc4bb35ab/src/SimpleBusCommandBusBundle.php#L17

**Comment by truckee** [comment]
Here's where I went astray perhaps. I did a search for `symfony user manager` and came across [your article](https://medium.com/@ro0NL/adding-user-management-to-your-symfony-application-ceeefe2a2e9) from 2018. I'll try following current doc's installation instead!

**Comment by ro0NL** [comment]
You're right, the article is outdated meanwhile :) see https://github.com/msgphp/msgphp/issues/328, it's on my list still to actualize it.

in general https://github.com/msgphp/symfony-demo-app holds the latest setup overall.

**Comment by ro0NL** [comment]
@truckee i assume the problem for now is solved then.
