### ISSUE TITLE
iterable is not a collection in . (which is being imported from "/app/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type. 

### ISSUE THREAD

**Issue by dvc** [msgphp/msgphp#370]
Hello everybody!

I have a bug after composer update (api-platform/* and msgphp/*)

```shell
$ php bin/console c:cl

 // Clearing the cache for the dev environment with debug true                                                          


In FileLoader.php line 166:
                                                                                                                                                                            
  iterable is not a collection in . (which is being imported from "/app/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.  
```

```shell
$ cat config/routes/api_platform.yaml 
api_platform:
    resource: .
    type: api_platform
    prefix: '/api'
```

```shell
$ cat config/packages/msgphp_user.yaml 
msgphp_user:
    class_mapping:
        MsgPhp\User\User: App\Entity\User\User
        MsgPhp\User\Role: App\Entity\User\Role
        MsgPhp\User\UserRole: App\Entity\User\UserRole
    default_id_type: uuid
    id_type_mapping:
        MsgPhp\User\UserId: uuid
    role_providers:
        default: [ !php/const App\Security\UserRolesProvider::ROLE_USER ]
        1: App\Security\UserRolesProvider
        2: MsgPhp\User\Role\UserRoleProvider

```

```shell
$ cat config/packages/doctrine.yaml 
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                driver: 'pdo_pgsql'
                server_version: '11.1'
                schema_filter: ~^(?!data_version)~
                url: '%env(resolve:DATABASE_URL)%'
            audit:
                # configure these for your database server
                driver: 'pdo_pgsql'
                server_version: '11.1'
                schema_filter: ~^(?!data_version)~
                url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
...
```

```shell
$ composer info | grep "symfony/framework\|api\|msgphp\|doctrine"
api-platform/api-pack               v1.2.0             A pack for API Platform
api-platform/core                   v2.4.7             Build a fully-featured hypermedia or GraphQL API in minutes
api-platform/schema-generator       v2.1.0             Various tools to generate a data model based on Schema.org vocables
doctrine/annotations                v1.8.0             Docblock Annotations Parser
doctrine/cache                      v1.8.0             Caching library offering an object-oriented API for many cache backends
doctrine/collections                v1.6.2             PHP Doctrine Collections library that adds additional functionality on top of PHP arrays.
doctrine/common                     v2.11.0            PHP Doctrine Common project is a library that provides additional functionality that other Doctrine projects depend on such as better reflection support, persistenc...
doctrine/data-fixtures              v1.3.2             Data Fixtures for all Doctrine Object Managers
doctrine/dbal                       v2.9.2             Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.
doctrine/doctrine-bundle            1.11.2             Symfony DoctrineBundle
doctrine/doctrine-cache-bundle      1.3.5              Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle   3.2.2              Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle v1.3.2             Symfony DoctrineMigrationsBundle
doctrine/event-manager              v1.0.0             Doctrine Event Manager component
doctrine/inflector                  v1.3.0             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator               1.2.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                      1.1.0              PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                 v1.8.1             Database Schema migrations using Doctrine DBAL
doctrine/orm                        v2.6.4             Object-Relational-Mapper for PHP
doctrine/persistence                1.1.1              The Doctrine Persistence project is a set of shared interfaces and functionality that the different Doctrine object mappers share.
doctrine/reflection                 v1.0.0             Doctrine Reflection component
dunglas/doctrine-json-odm           0.1.3              An object document mapper for Doctrine ORM using JSON types of modern RDBMS.
msgphp/domain                       v0.13.0            A dependency-free package to help building a business domain layer
msgphp/user                         v0.13.0            A domain layer providing basic user management
msgphp/user-bundle                  v0.13.0            Basic user management (the `User` domain)
opsway/doctrine-dbal-postgresql     v0.8.1             Extensions for support Postgres in Doctrine DBAL & DQL
oro/doctrine-extensions             dev-master 2dbedcc Doctrine Extensions for MySQL and PostgreSQL.
ramsey/uuid-doctrine                1.5.0              Allow the use of a ramsey/uuid UUID as Doctrine field type.
ruvents/doctrine-fixes-bundle       0.1.1              RUVENTS Doctrine Fixes Bundle
scienta/doctrine-json-functions     4.0.2              A set of extensions to Doctrine 2 that add support for json query functions.
symfony/doctrine-bridge             v4.3.5             Symfony Doctrine Bridge
symfony/framework-bundle            v4.3.5             Symfony FrameworkBundle
```
What can i do with it?

**Comment by ro0NL** [comment]
hi @dvc can you run with `-vvv` to provide a stack trace, in general not sure what happens :) looks related to Symfony Routing.

**Comment by ro0NL** [comment]
i believe there should be a previous exception hiding the actual error (`iterable is not a collection`), this is the stack trace we're looking for.

it should be displayed in CLI below the `In FileLoader.php line 166:` block

**Comment by brainstorm1313** [comment]
here you are
`
$ bin/console cache:clear --env=dev -vvv

 // Clearing the cache for the dev environment with debug true

 // Warming up cache...


In FileLoader.php line 166:

  [Symfony\Component\Config\Exception\LoaderLoadException]
  iterable is not a collection in . (which is being imported from "/app/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.


Exception trace:
  at /app/vendor/symfony/config/Loader/FileLoader.php:166
 Symfony\Component\Config\Loader\FileLoader->doImport() at /app/vendor/symfony/config/Loader/FileLoader.php:90
 Symfony\Component\Config\Loader\FileLoader->import() at /app/vendor/symfony/routing/Loader/YamlFileLoader.php:190
 Symfony\Component\Routing\Loader\YamlFileLoader->parseImport() at /app/vendor/symfony/routing/Loader/YamlFileLoader.php:84
 Symfony\Component\Routing\Loader\YamlFileLoader->load() at /app/vendor/symfony/config/Loader/FileLoader.php:151
 Symfony\Component\Config\Loader\FileLoader->doImport() at /app/vendor/symfony/config/Loader/FileLoader.php:90
 Symfony\Component\Config\Loader\FileLoader->import() at /app/vendor/symfony/routing/Loader/GlobFileLoader.php:32
 Symfony\Component\Routing\Loader\GlobFileLoader->load() at /app/vendor/symfony/routing/RouteCollectionBuilder.php:371
 Symfony\Component\Routing\RouteCollectionBuilder->load() at /app/vendor/symfony/routing/RouteCollectionBuilder.php:62
 Symfony\Component\Routing\RouteCollectionBuilder->import() at /app/src/Kernel.php:56
 App\Kernel->configureRoutes() at /app/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:87
 App\Kernel->loadRoutes() at /app/vendor/symfony/routing/Loader/ObjectRouteLoader.php:70
 Symfony\Component\Routing\Loader\ObjectRouteLoader->load() at /app/vendor/symfony/config/Loader/DelegatingLoader.php:40
 Symfony\Component\Config\Loader\DelegatingLoader->load() at /app/vendor/symfony/framework-bundle/Routing/DelegatingLoader.php:72
 Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader->load() at /app/vendor/symfony/framework-bundle/Routing/Router.php:70
 Symfony\Bundle\FrameworkBundle\Routing\Router->getRouteCollection() at /app/vendor/symfony/routing/Router.php:417
 Symfony\Component\Routing\Router->getMatcherDumperInstance() at /app/vendor/symfony/routing/Router.php:311
 Symfony\Component\Routing\Router->Symfony\Component\Routing\{closure}() at /app/vendor/symfony/config/ResourceCheckerConfigCacheFactory.php:43
 Symfony\Component\Config\ResourceCheckerConfigCacheFactory->cache() at /app/vendor/symfony/routing/Router.php:324
 Symfony\Component\Routing\Router->getMatcher() at /app/vendor/symfony/framework-bundle/Routing/Router.php:87
 Symfony\Bundle\FrameworkBundle\Routing\Router->warmUp() at /app/vendor/symfony/framework-bundle/CacheWarmer/RouterCacheWarmer.php:47
 Symfony\Bundle\FrameworkBundle\CacheWarmer\RouterCacheWarmer->warmUp() at /app/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:97
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /app/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:194
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /app/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:129
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /app/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:952
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/framework-bundle/Console/Application.php:87
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/framework-bundle/Console/Application.php:73
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /app/bin/console:40

In TypeResolver.php line 399:

  [RuntimeException]
  iterable is not a collection


Exception trace:
  at /app/vendor/phpdocumentor/type-resolver/src/TypeResolver.php:399
 phpDocumentor\Reflection\TypeResolver->resolveCollection() at /app/vendor/phpdocumentor/type-resolver/src/TypeResolver.php:224
 phpDocumentor\Reflection\TypeResolver->parseTypes() at /app/vendor/phpdocumentor/type-resolver/src/TypeResolver.php:146
 phpDocumentor\Reflection\TypeResolver->resolve() at /app/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/Var_.php:68
 phpDocumentor\Reflection\DocBlock\Tags\Var_::create() at n/a:n/a
 call_user_func_array() at /app/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php:201
 phpDocumentor\Reflection\DocBlock\StandardTagFactory->createTag() at /app/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php:122
 phpDocumentor\Reflection\DocBlock\StandardTagFactory->create() at /app/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php:231
 phpDocumentor\Reflection\DocBlockFactory->parseTagBlock() at /app/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php:96
 phpDocumentor\Reflection\DocBlockFactory->create() at /app/vendor/symfony/property-info/Extractor/PhpDocExtractor.php:196
 Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor->getDocBlockFromProperty() at /app/vendor/symfony/property-info/Extractor/PhpDocExtractor.php:167
 Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor->getDocBlock() at /app/vendor/symfony/property-info/Extractor/PhpDocExtractor.php:74
 Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor->getShortDescription() at /app/vendor/symfony/property-info/PropertyInfoExtractor.php:109
 Symfony\Component\PropertyInfo\PropertyInfoExtractor->extract() at /app/vendor/symfony/property-info/PropertyInfoExtractor.php:58
 Symfony\Component\PropertyInfo\PropertyInfoExtractor->getShortDescription() at /app/vendor/api-platform/core/src/Bridge/Symfony/PropertyInfo/Metadata/Property/PropertyInfoPropertyMetadataFactory.php:59
 ApiPlatform\Core\Bridge\Symfony\PropertyInfo\Metadata\Property\PropertyInfoPropertyMetadataFactory->create() at /app/vendor/api-platform/core/src/Metadata/Property/Factory/InheritedPropertyMetadataFactory.php:40
 ApiPlatform\Core\Metadata\Property\Factory\InheritedPropertyMetadataFactory->create() at /app/vendor/api-platform/core/src/Bridge/Doctrine/Orm/Metadata/Property/DoctrineOrmPropertyMetadataFactory.php:42
 ApiPlatform\Core\Bridge\Doctrine\Orm\Metadata\Property\DoctrineOrmPropertyMetadataFactory->create() at /app/vendor/api-platform/core/src/Metadata/Property/Factory/SerializerPropertyMetadataFactory.php:49
 ApiPlatform\Core\Metadata\Property\Factory\SerializerPropertyMetadataFactory->create() at /app/vendor/api-platform/core/src/Metadata/Property/Factory/AnnotationSubresourceMetadataFactory.php:44
 ApiPlatform\Core\Metadata\Property\Factory\AnnotationSubresourceMetadataFactory->create() at /app/vendor/api-platform/core/src/Metadata/Property/Factory/AnnotationPropertyMetadataFactory.php:46
 ApiPlatform\Core\Metadata\Property\Factory\AnnotationPropertyMetadataFactory->create() at /app/vendor/api-platform/core/src/Metadata/Property/Factory/ExtractorPropertyMetadataFactory.php:45
 ApiPlatform\Core\Metadata\Property\Factory\ExtractorPropertyMetadataFactory->create() at /app/vendor/api-platform/core/src/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactory.php:82
 ApiPlatform\Core\Bridge\Symfony\Validator\Metadata\Property\ValidatorPropertyMetadataFactory->create() at /app/vendor/api-platform/core/src/Metadata/Property/Factory/CachedPropertyMetadataFactory.php:47
 ApiPlatform\Core\Metadata\Property\Factory\CachedPropertyMetadataFactory->ApiPlatform\Core\Metadata\Property\Factory\{closure}() at /app/vendor/api-platform/core/src/Cache/CachedTrait.php:44
 ApiPlatform\Core\Metadata\Property\Factory\CachedPropertyMetadataFactory->getCached() at /app/vendor/api-platform/core/src/Metadata/Property/Factory/CachedPropertyMetadataFactory.php:48
 ApiPlatform\Core\Metadata\Property\Factory\CachedPropertyMetadataFactory->create() at /app/vendor/api-platform/core/src/Operation/Factory/SubresourceOperationFactory.php:70
 ApiPlatform\Core\Operation\Factory\SubresourceOperationFactory->computeSubresourceOperations() at /app/vendor/api-platform/core/src/Operation/Factory/SubresourceOperationFactory.php:50
 ApiPlatform\Core\Operation\Factory\SubresourceOperationFactory->create() at /app/vendor/api-platform/core/src/Operation/Factory/CachedSubresourceOperationFactory.php:44
 ApiPlatform\Core\Operation\Factory\CachedSubresourceOperationFactory->ApiPlatform\Core\Operation\Factory\{closure}() at /app/vendor/api-platform/core/src/Cache/CachedTrait.php:44
 ApiPlatform\Core\Operation\Factory\CachedSubresourceOperationFactory->getCached() at /app/vendor/api-platform/core/src/Operation/Factory/CachedSubresourceOperationFactory.php:45
 ApiPlatform\Core\Operation\Factory\CachedSubresourceOperationFactory->create() at /app/vendor/api-platform/core/src/Bridge/Symfony/Routing/ApiLoader.php:111
 ApiPlatform\Core\Bridge\Symfony\Routing\ApiLoader->load() at /app/vendor/symfony/config/Loader/FileLoader.php:151
 Symfony\Component\Config\Loader\FileLoader->doImport() at /app/vendor/symfony/config/Loader/FileLoader.php:90
 Symfony\Component\Config\Loader\FileLoader->import() at /app/vendor/symfony/routing/Loader/YamlFileLoader.php:190
 Symfony\Component\Routing\Loader\YamlFileLoader->parseImport() at /app/vendor/symfony/routing/Loader/YamlFileLoader.php:84
 Symfony\Component\Routing\Loader\YamlFileLoader->load() at /app/vendor/symfony/config/Loader/FileLoader.php:151
 Symfony\Component\Config\Loader\FileLoader->doImport() at /app/vendor/symfony/config/Loader/FileLoader.php:90
 Symfony\Component\Config\Loader\FileLoader->import() at /app/vendor/symfony/routing/Loader/GlobFileLoader.php:32
 Symfony\Component\Routing\Loader\GlobFileLoader->load() at /app/vendor/symfony/routing/RouteCollectionBuilder.php:371
 Symfony\Component\Routing\RouteCollectionBuilder->load() at /app/vendor/symfony/routing/RouteCollectionBuilder.php:62
 Symfony\Component\Routing\RouteCollectionBuilder->import() at /app/src/Kernel.php:56
 App\Kernel->configureRoutes() at /app/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:87
 App\Kernel->loadRoutes() at /app/vendor/symfony/routing/Loader/ObjectRouteLoader.php:70
 Symfony\Component\Routing\Loader\ObjectRouteLoader->load() at /app/vendor/symfony/config/Loader/DelegatingLoader.php:40
 Symfony\Component\Config\Loader\DelegatingLoader->load() at /app/vendor/symfony/framework-bundle/Routing/DelegatingLoader.php:72
 Symfony\Bundle\FrameworkBundle\Routing\DelegatingLoader->load() at /app/vendor/symfony/framework-bundle/Routing/Router.php:70
 Symfony\Bundle\FrameworkBundle\Routing\Router->getRouteCollection() at /app/vendor/symfony/routing/Router.php:417
 Symfony\Component\Routing\Router->getMatcherDumperInstance() at /app/vendor/symfony/routing/Router.php:311
 Symfony\Component\Routing\Router->Symfony\Component\Routing\{closure}() at /app/vendor/symfony/config/ResourceCheckerConfigCacheFactory.php:43
 Symfony\Component\Config\ResourceCheckerConfigCacheFactory->cache() at /app/vendor/symfony/routing/Router.php:324
 Symfony\Component\Routing\Router->getMatcher() at /app/vendor/symfony/framework-bundle/Routing/Router.php:87
 Symfony\Bundle\FrameworkBundle\Routing\Router->warmUp() at /app/vendor/symfony/framework-bundle/CacheWarmer/RouterCacheWarmer.php:47
 Symfony\Bundle\FrameworkBundle\CacheWarmer\RouterCacheWarmer->warmUp() at /app/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerAggregate.php:97
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /app/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:194
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /app/vendor/symfony/framework-bundle/Command/CacheClearCommand.php:129
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /app/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:952
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/framework-bundle/Console/Application.php:87
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/framework-bundle/Console/Application.php:73
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /app/bin/console:40
`

**Comment by brainstorm1313** [comment]
Hello, @ro0NL! Any ideas?

**Comment by ro0NL** [comment]
hi @brainstorm1313 i think the issue comes from `phpdocumentor/type-resolver`, but im not sure what class/docblock is causing it (could be a msgphp)

i think it can be discovered somewhere along  the files here

```
Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor->getShortDescription() at /app/vendor/symfony/property-info/PropertyInfoExtractor.php:109
 Symfony\Component\PropertyInfo\PropertyInfoExtractor->extract() at /app/vendor/symfony/property-info/PropertyInfoExtractor.php:58
 Symfony\Component\PropertyInfo\PropertyInfoExtractor->getShortDescription() at /app/vendor/api-platform/core/src/Bridge/Symfony/PropertyInfo/Metadata/Property/PropertyInfoPropertyMetadataFactory.php:59
 ApiPlatform\Core\Bridge\Symfony\PropertyInfo\Metadata\Property\PropertyInfoPropertyMetadataFactory->create() at /app/vendor/api-platform/core/src/Metadata/Property/Factory/InheritedPropertyMetadataFactory.php:40
```

still not sure what's happening, as i didnt had such issues with the demo app.

comparing v1.0.1 (https://github.com/phpDocumentor/TypeResolver/blob/2e32a6d48972b2c1976ed5d8967145b6cec4a4a9/src/TypeResolver.php#L394) with master *(https://github.com/phpDocumentor/TypeResolver/blob/5ad886e77d4a28df9fd0c81c9a3cc191799e8f5f/src/TypeResolver.php#L395), it seems patched already :)

**Comment by brainstorm1313** [comment]
Thanks a lot! I updated to phpDocumentor/TypeResolver:dev-master and the problem is gone!
