### ISSUE TITLE
Deprecation notice in Symfony v4.4

### ISSUE THREAD

**Issue by jkabat** [msgphp/msgphp#371]
FYI: `The "Symfony\Bundle\SecurityBundle\DataCollector\SecurityDataCollector" class is considered final since Symfony 4.4. It may change without further notice as of its next major version. You should not extend it from "MsgPhp\User\Infrastructure\Security\DataCollector".`

**Comment by ro0NL** [comment]
initially i knew this would happen :joy: 

https://github.com/msgphp/msgphp/blob/82899c2ae3688230719ca7ebbda1112b4ea176b2/src/User/Infrastructure/Security/DataCollector.php#L26

Thanks for mentioning, i'll take care of this ASAP :)

**Comment by jkabat** [comment]
@ro0NL can you please tag new version? Or you still have some things in mind before doing so?
