### ISSUE TITLE
Doctrine User table inheritance issue

### ISSUE THREAD

**Issue by jkabat** [msgphp/msgphp#373]
I'm not sure if this is the right place to discuss, but maybe at least you guys can give me a hint.

My custom App\Entity\User entity extends abstract MsgPhp\User\User. My inheritance is defined in following manner:
```php
/**
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="discriminator", type="string")
 * @ORM\DiscriminatorMap({"user" = "User", "expert_user" = "ExpertUser"})
 */
```

However when I'm trying to select from ExpertUser:
```php
$this->_em->createQueryBuilder()
    ->select('expert_user')
    ->from(ExpertUser::class, 'expert_user')
    ->innerJoin('expert_user...', '...') // expert user only relations
    ->where('...')
```
it always ends up with an exception:
```php
An exception occurred while executing 'SELECT u0_.id AS id_0... FROM expert_user e1_ INNER JOIN user u0_ ON e1_.id = u0_.id INNER JOIN user u0_ ON e1_.id = u0_.id...'

SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'u0_'
```

I did a simple debugging and it seems that [SqlWalker](https://github.com/doctrine/orm/blob/v2.7.0/lib/Doctrine/ORM/Query/SqlWalker.php#L349) sees 2 parents of an ExpertUser entity and joins User table twice:

```php
In SqlWalker.php line 346:
array:2 [▼
  0 => "App\Entity\User"
  1 => "MsgPhp\User\User"
]
```

Is there any chance for me to fix the hierarchy in order to get generated proper SQL?

**Comment by jkabat** [comment]
It is possible to update class metadata just before query, but is it the best option?

**Comment by ro0NL** [comment]
hi @jkabat i need to check a bit :) in general we use a regular-ish doctrine setup: `mapped super class > entity > child entity`.

So im curious why it tries to join `MsgPhp\User\User`, which is a mapped super class. I'll try to replicate asap.
