### ISSUE TITLE
Update roles in runtime

### ISSUE THREAD

**Issue by jkabat** [msgphp/msgphp#376]
Sometimes you need to update user identity during the same logged in session (eg: change user role from ROLE_PREMIUM_USER back to ROLE_USER). Symfony natively does not support it. You have to logout user and let him log again, which is not very user friendly.

In discussion at https://github.com/symfony/symfony/issues/12025 some users suggest to update user token with new roles, but that is not very easy thing to do via msgphp-user-bundle as UserIdentity is final and cannot be extended with whatever logic developer would like to use.

What would be preferred way to handle such use cases?

ATM Im using permission system rather than roles which is kind of depressing because for things like that should user roles be used... What do you think?

**Comment by ro0NL** [comment]
HI @jkabat 

I think i'd prefer e.g. https://github.com/symfony/symfony/issues/12025#issuecomment-219726353, which should not be blocked our `UserIdentity` IIUC.

Overall i agree with https://github.com/symfony/symfony/issues/12025#issuecomment-411719302 :D

Even if you need to re-login a user, that can be done programmatically as the user was already logged in. Which perhaps is the best approach.

**Comment by jkabat** [comment]
I have reread Kobzol suggestion again and yes it seems to be a solution where you can leave UserIdentity intact. I will reopen if anything arise. Thanks for such prompt answer.
