### ISSUE TITLE
Declaration error of handle in symfony update

### ISSUE THREAD

**Issue by mdimitris** [msgphp/msgphp#377]
When I try to update my symfony installation (after implementing this https://github.com/msgphp/msgphp/commit/db93d2e74825051f4d6c82e84d1d6b55331180ac) from 4.1 to 4.4 I receive the following error:

`Compile Error: Declaration of MsgPhp\Domain\Infra\Messenger\Middleware\ConsoleMessageReceiverMiddleware::handle($message, callable $next) must be compatible with Symfony\Component\Messenger\Middleware\MiddlewareInterface::handle(Symfony\Component\Messenger\Envelope $envelope, Symfony\Component\Messenger\Middleware\StackInterface $stack): Symfony\Component\Messenger\Envelope
`

I would appreciate any help...

**Comment by ro0NL** [comment]
hi @mdimitris i'll take care of it this weekend. together with #372 i need to perform some updates still.

**Comment by ro0NL** [comment]
Hi @mdimitris , sorry but i just checked and the `ConsoleMessageReceiverMiddleware` is removed as of v0.11 :) Updating msgphp should solve it.

**Comment by mdimitris** [comment]
Hi @ro0NL ! Thanks a lot for the update! I ll use it asap. :) Have a nice day!
