### ISSUE TITLE
Alias error

### ISSUE THREAD

**Issue by ollietb** [msgphp/msgphp#395]
After installing the user bundle and running `make:user `command according to [this article ](https://medium.com/@ro0NL/adding-user-management-to-your-symfony-application-ceeefe2a2e9) I get an error when saving the registration form.
`Error: Expected Doctrine\ORM\Query\Lexer::T_MEMBER, got '='`
It looks like the problem is with the `getAlias()` method in DomainEntityRepositoryTrait when checking for uniqueness. The generated DQL is `SELECT 1 FROM App\Entity\Member member WHERE member.credential.email = :credential_email` which fails. The `getAlias` method returns `member` where it should return `m` - when I manually edit the alias in the DQL `SELECT 1 FROM App\Entity\Member m WHERE m.credential.email = :credential_email` is working.

My class mappings are like this
```
msgphp_user:
    class_mapping:
        MsgPhp\User\User: App\Entity\Member
```

**Comment by ollietb** [comment]
I've realised that member is a reserved word, so closing this issue

**Comment by ro0NL** [comment]
@ollietb is it worth quoting the alias? I think having a class named `Member` should be possible :/
