### ISSUE TITLE
Inexistent Relation in Role

### ISSUE THREAD

**Issue by gbelvedere** [msgphp/msgphp#398]
After installation with default settings (with EmailPassword), when running: 

bin/console doctrine:schema:update --force

I get: 

"Column name `name` referenced for relation from App\Entity\UserRole towards MsgPhp\User\
  Role does not exist."

any clue? thanks!

**Comment by gbelvedere** [comment]
sorry, wrong package

**Comment by gbelvedere** [comment]
Sorry to reopen, problem is related to https://github.com/msgphp/user-bundle
Reinstalled the bundle and dependencies but still the same, after the wizard: 

After installation with default settings (with EmailPassword), when running:

bin/console doctrine:schema:update --force

I get:

Column name "name" referenced for relation from App\Entity\UserRole towards MsgPhp\User
Role does not exist."

I see msgphp/user/Role.php having the method getName, whats missing here?

**Comment by gbelvedere** [comment]
Oh, the command is wrong, is: 
```
php bin/console debug:config doctrine orm
```
I did'nt know it and it is space not a colon...anyway, here is the output: 

```
Current configuration for "doctrine.orm"
========================================

resolve_target_entities:
    MsgPhp\User\User: App\Entity\User
    MsgPhp\User\UserId: MsgPhp\User\ScalarUserId
    MsgPhp\User\Credential\Credential: MsgPhp\User\Credential\EmailPassword
default_entity_manager: default
entity_managers:
    default:
        hydrators:
            msgphp_scalar: MsgPhp\Domain\Infrastructure\Doctrine\Hydration\ScalarHydrator
            msgphp_single_scalar: MsgPhp\Domain\Infrastructure\Doctrine\Hydration\SingleScalarHydrator
        mappings:
            msgphp:
                dir: /var/www/vagrant/website/var/cache/dev/msgphp/doctrine-mapping
                type: xml
                prefix: MsgPhp
                is_bundle: false
                mapping: true
            App:
                is_bundle: false
                type: annotation
                dir: /var/www/vagrant/website/src/Entity
                prefix: App\Entity
                alias: App
                mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        query_cache_driver:
            type: null
        metadata_cache_driver:
            type: null
        result_cache_driver:
            type: null
        class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
        default_repository_class: Doctrine\ORM\EntityRepository
        quote_strategy: doctrine.orm.quote_strategy.default
        entity_listener_resolver: null
        repository_factory: doctrine.orm.container_repository_factory
        filters: {  }
auto_generate_proxy_classes: true
proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
proxy_namespace: Proxies

2020-06-11T04:28:28+00:00 [info] User Deprecated: Since symfony/dependency-injection 5.1: "Symfony\Component\DependencyInjection\Loader\Configurator\ref()" is deprecated, use "service()" instead.
2020-06-11T04:28:28+00:00 [info] User Deprecated: Since symfony/dependency-injection 5.1: "Symfony\Component\DependencyInjection\Loader\Configurator\ref()" is deprecated, use "service()" instead.
2020-06-11T04:28:28+00:00 [info] User Deprecated: Since symfony/dependency-injection 5.1: "Symfony\Component\DependencyInjection\Loader\Configurator\inline()" is deprecated, use "inline_service()" instead.
2020-06-11T04:28:28+00:00 [info] User Deprecated: Since symfony/dependency-injection 5.1: "Symfony\Component\DependencyInjection\Loader\Configurator\ref()" is deprecated, use "service()" instead.
2020-06-11T04:28:28+00:00 [info] User Deprecated: Since symfony/dependency-injection 5.1: "Symfony\Component\DependencyInjection\Loader\Configurator\ref()" is deprecated, use "service()" instead.
2020-06-11T04:28:28+00:00 [info] User Deprecated: The "Symfony\Bundle\SecurityBundle\DataCollector\SecurityDataCollector" class is considered final. It may change without further notice as of its next major version. You should not extend it from "MsgPhp\User\Infrastructure\Security\DataCollector".

```

I'm on a vagrant container, with PHP 7.4.6 and Symfony 5.1.0

**Comment by ro0NL** [comment]
@gbelvedere `MsgPhp\User\Role: App\Entity\Role` is somehow missing under `resolve_target_entities`

the installation command (make:user:msgphp) should have generated a config file defining the class mapping as such, see e.g. the demo app https://github.com/msgphp/symfony-demo-app/blob/7d37297dd5dd113ed361603a125fa5ff44b09263/config/packages/msgphp_user.php#L18 (note it uses PHP format)

this class mapping (in our bundle config) is then passed the doctrine's `resolve_target_entities` config.

In general im curious why the installer did create the entities, but not the corresponding config. Unless you did things manually, it should have generated a `config/packages/msgphp_user.make.php` isnt it?

**Comment by gbelvedere** [comment]
the file is there: 
```
<?php

// generated by `make:user:msgphp`
// this configuration may be merged into your existing application configuration

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use function Symfony\Component\DependencyInjection\Loader\Configurator\ref;

return function (ContainerConfigurator $container) {
    $container->extension('msgphp_user', array (
  'class_mapping' => 
  array (
    'MsgPhp\\User\\Role' => 'App\\Entity\\Role',
    'MsgPhp\\User\\UserRole' => 'App\\Entity\\UserRole',
  ),
  'role_providers' => 
  array (
    'default' => 
    array (
      0 => 'ROLE_USER',
    ),
    0 => 'MsgPhp\\User\\Role\\UserRoleProvider',
  ),
));

    $container->services()
        ->defaults()
            ->private()
            ->autoconfigure()
            ->autowire()

        ->set(App\Console\ClassContextElementFactory::class)
        ->alias(MsgPhp\Domain\Infrastructure\Console\Context\ClassContextElementFactory::class, App\Console\ClassContextElementFactory::class)
    ;
};

```

I think something went wrong with the doctrine installation, I ended installing it manually. I'll try to rollback and install it all again and let you know, may be the error was somewhere else.

**Comment by ro0NL** [comment]
Hi @gbelvedere can you also share msgphp's actual config: `bin/console debug:config msgphp_user`

just to be sure the generated config is used :)

i'll try to reproduce in a few days; i need to prepare a new release as well :)

**Comment by gbelvedere** [comment]
sorry for the delay, here it is: 

Current configuration for extension with alias "msgphp_user"
============================================================

msgphp_user:
    class_mapping:
        MsgPhp\User\User: App\Entity\User
        MsgPhp\User\UserId: MsgPhp\User\ScalarUserId
        MsgPhp\User\Credential\Credential: MsgPhp\User\Credential\EmailPassword
    id_type_mapping:
        MsgPhp\User\UserId: integer
    commands:
        MsgPhp\User\Command\CreateRole: false
        MsgPhp\User\Command\DeleteRole: false
        MsgPhp\User\Command\CreateUser: true
        MsgPhp\User\Command\DeleteUser: true
        MsgPhp\User\Command\ChangeUserCredential: true
        MsgPhp\User\Command\ConfirmUser: false
        MsgPhp\User\Command\DisableUser: false
        MsgPhp\User\Command\EnableUser: false
        MsgPhp\User\Command\CancelUserPasswordRequest: true
        MsgPhp\User\Command\RequestUserPassword: true
        MsgPhp\User\Command\ResetUserPassword: true
        MsgPhp\User\Command\AddUserAttributeValue: false
        MsgPhp\User\Command\ChangeUserAttributeValue: false
        MsgPhp\User\Command\DeleteUserAttributeValue: false
        MsgPhp\User\Command\AddUserEmail: false
        MsgPhp\User\Command\DeleteUserEmail: false
        MsgPhp\User\Command\ConfirmUserEmail: false
        MsgPhp\User\Command\AddUserRole: false
        MsgPhp\User\Command\DeleteUserRole: false
    credential_field: credential
    username_lookup: {  }
    role_providers:
        default:
            - ROLE_USER
    doctrine:
        auto_sync_username: true
    username_field: credential.email

**Comment by gbelvedere** [comment]
I tried to clean up and re-install: 


```
vagrant@vagrant:/var/www/vagrant/website$ composer require msgphp/user-bundle
Using version ^0.15.1 for msgphp/user-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Package operations: 0 installs, 0 updates, 18 removals
  - Removing symfony/validator (v5.1.0)
  - Removing symfony/security-http (v5.1.0)
  - Removing symfony/security-guard (v5.1.0)
  - Removing symfony/security-csrf (v5.1.0)
  - Removing symfony/security-core (v5.1.0)
  - Removing symfony/security-bundle (v5.1.0)
  - Removing symfony/redis-messenger (v5.1.0)
  - Removing symfony/property-info (v5.1.0)
  - Removing symfony/property-access (v5.1.0)
  - Removing symfony/polyfill-intl-icu (v1.17.0)
  - Removing symfony/options-resolver (v5.1.0)
  - Removing symfony/messenger (v5.1.0)
  - Removing symfony/intl (v5.1.0)
  - Removing symfony/inflector (v5.1.0)
  - Removing symfony/form (v5.1.0)
  - Removing symfony/doctrine-messenger (v5.1.0)
  - Removing symfony/amqp-messenger (v5.1.0)
  - Removing sebastian/diff (4.0.1)
Writing lock file
Generating optimized autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
48 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Executing script cache:clear [OK]
Executing script assets:install public [OK]

vagrant@vagrant:/var/www/vagrant/website$ bin/console make:user:msgphp
[error] Error thrown while running command "'make:user:msgphp'". Message: "There are no commands defined in the "make:user" namespace.

Did you mean one of these?
    make
    make:serializer"



  There are no commands defined in the "make:user" namespace.

  Did you mean one of these?
      make
      make:serializer


vagrant@vagrant:/var/www/vagrant/website$ composer require maker --dev
Using version ^1.19 for symfony/maker-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.1.*"
Nothing to install or update
Generating optimized autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
48 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Executing script cache:clear [OK]
Executing script assets:install public [OK]

vagrant@vagrant:/var/www/vagrant/website$
vagrant@vagrant:/var/www/vagrant/website$ bin/console make:user:msgphp
[error] Error thrown while running command "'make:user:msgphp'". Message: "There are no commands defined in the "make:user" namespace.

Did you mean one of these?
    make
    make:serializer"



  There are no commands defined in the "make:user" namespace.

  Did you mean one of these?
      make
      make:serializer


```

**Comment by ro0NL** [comment]
Hi @gbelvedere 

i just realized, the default Kernel was updated as of SF5 (im still on SF4 myself).

In SF4 the kernel was still loading PHP config files: https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/4.2/src/Kernel.php#L16

However as of SF5 it only supports YAML by default: https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/5.1/src/Kernel.php#L16

So this is likely to break MsgPHP by default (aka fresh install).

Perhaps fornow load those PHP config files yourself, or rewrite the generated config in YAML.

Im not sure why the `make:user:msgphp` command became unavailable, will look into it :+1: 

I also let the bundle generate YAML config asap.

**Comment by maddy2101** [comment]
Hi, I run into the same problem. My instance is a fresh symfony 5.1, and the command worked, but I end up with the initial error message when running `bin/console doctrine:schema:create`.

My chose config was NicknamePassword, in case that makes any difference.

I also have the generated php config file, but all the rest of my config is yaml. So when you advise to `load those PHP config files yourself`, how would I do that? I am not experienced enough to rewrite it to yaml.

**Comment by rusanter** [comment]
@maddy2101 I think this is the right configuration in your case (and mine as well):
```
// config/msgphp_user.make.yaml
msgphp_user:
    class_mapping:
        MsgPhp\User\User: App\Entity\User
        MsgPhp\User\Credential\Credential: MsgPhp\User\Credential\EmailPassword
        MsgPhp\User\Role: App\Entity\Role
        MsgPhp\User\UserRole: App\Entity\UserRole
    role_providers:
        default:
            - ROLE_USER
        0: MsgPhp\User\Role\UserRoleProvider
```
