### ISSUE TITLE
Symfonys getUser() method returns the UserIdentity instead of the App\Entity\User Entity

### ISSUE THREAD

**Issue by eltomato89** [msgphp/msgphp#400]
Hi,

I started with a fresh Symfony 5.0.0 installation and added the user-bundle to it.
After running the "bin/console make:user:msgphp", there was a "User.php" entity.
I added multiple properties to it (firstname, lastname, ...)

The TokenStorage returns only the MsgPhp\User\Infrastructure\Security\UserIdentity but not the created User Entity.

Is this the correct behavior? How do I get my User entity then?

**Comment by ro0NL** [comment]
Hi @eltomato89, yes this is the correct behavior; inspired by https://stovepipe.systems/post/decoupling-your-security-user

Generally spoken, you can get the user entity using the repository in between; `$userRepo->find($identity->getUserId())`

In templates using `{% set user = msgphp_user.current %}`

Or in controllers using a [`@ParamConverter`](https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html), see for an example: https://github.com/msgphp/symfony-demo-app/blob/7d37297dd5dd113ed361603a125fa5ff44b09263/src/Controller/ProfileController.php#L36-L39
