### ISSUE TITLE
Multiple user entities

### ISSUE THREAD

**Issue by ro0NL** [msgphp/msgphp#41]
From https://github.com/msgphp/symfony-demo-app/pull/6

Should be possible with our mapped super classes. Could be cool to have a demo with regular `User`s and `Admin` users or so (for demo purpose, i.e. `/login` vs. `/admin/login`).

**Comment by ro0NL** [comment]
@Evertt given this some thought, i think it be a good feature and we need to abstract it. You might want multiple other entities as well.

Creating the entities itself shouldnt be the problem with our mapped super class. The issue is we only know about one. But we can improve the config for that;

Current

```yaml
class_mapping:
  User: App\User
```

Proposed:

```yaml
class_mapping:
  User:
    default: App\User
    admin: App\AdminUser
```

This way we we can create all the services twice, and suffix service id's with e.g.  `.default` or `.admin`. Interfaces would be aliased to the default implem.

Sounds cool and should work out in general. What's worries me is all our services are autowired and thus use the default implem; e.g. `user:create` CLI command.

How would that work? Do you expect something here? E.g. should it ask which type of user to create first? Should it enable a `user-admin:create` command as well?

**Comment by Evertt** [comment]
> How would that work? Do you expect something here? E.g. should it ask which type of user to create first? Should it enable a user-admin:create command as well?

I would say you'd have one command which takes a parameter, something like `--type=admin`. If there is only one type then that parameter would default to the one. If there are multiple types and you omitted the parameter then the command should ask for it. Does that make sense to you?

I have my doubts about having a default user. In my particular example, I have 3 entities that extend from an abstract base class. So the base class can never be instantiated. And to me, none of the 3 entities is more "normal" or "special" than the others, so it would seem weird to me to have to label one of the entities as the default one.

If you need it, because you need all the interfaces to extend from some kind of base interface then I would prefer to label my abstract base class as the "default" one. But since that one can't be instantiated I'm not sure that's possible.

All in all I just don't quite understand yet how you picture this structure.

**Comment by ro0NL** [comment]
> it would seem weird to me to have to label one of the entities as the default one

It would be opt-in, using `default`  key in the class mapping triggers aliasing some FQCN services for autowiring. `"default"` is magic string yes.

> If you need it, because you need all the interfaces to extend from some kind of base interface then I would prefer to label my abstract base class as the "default" one.

We dont really "need" it, it's just because the bundle only registers a bunch of services it seems convenient to have. So you can still benefit from autowiring where it provides the default implem.

In casse a default implem is not mapped, you must use the explicit service id in your config (`msgphp.user.repository.admin` or so) or create an alias to our `UserRepositoryInterface` yourself.

> All in all I just don't quite understand yet how you picture this structure.

We give in on autowiring a bit. Lets say we map `default` + `admin` classes, then we create 2 `SecurityUserProvider` services `security.user_provider.default` and `<....>.admin` and map the arguments per case (i.e. first gets `repo.default`; second `repo.admin`). In case we have a "default", the FQCN service (`SecurtiyUserProvider`) is aliased to it.

It's a big step, as we currently heavily rely on the fact we know your class from `$map[OurUser::class]` and expect there's one.

**Comment by Evertt** [comment]
Ah yes of course, I understand now. Yes in that case it definitely makes sense to be able to define a default user entity.

In the case of a user provider, if the different user entities extend a base entity then you don't actually need multiple user providers AFAIK. Again I'm super new to Symfony, so maybe I'm missing something. So again, I have `Consumer`, `Supplier`, and `Admin`, which all extend an abstract class called `User`. But I can ask Doctrine to give me any of the three when I use the following code:

```php
$user = $this->get('doctrine.orm.default_entity_manager')
             ->getRepository(User::class)
             ->findOneBy(compact('email', 'password'));
```

And `$user` can end up being any of my 3 entities, so I wouldn't need to have multiple user providers for that. Am I correct?

**Comment by ro0NL** [comment]
@Evertt im having doubts about my proposed config. It's possible.. but i think we increase complexity for no real gain (at this point). That is; having 2 independent user entities.

However, what could be an interesting path is to check if entities have an inheritance mapping somewhere. I.e. with doctrine we could read the discriminator map.

Im not too experienced with doctrine's inheritance mapping, so it needs some thought to figure out a path. In general i think we need to look at SINGLE_TABLE and JOINED types.

>  I have Consumer, Supplier, and Admin, which all extend an abstract class called User.

What's your setup actually? Your User is a mapped super class? That's a 3rd type of inheritance...

Complex topic for sure :)

**Comment by Evertt** [comment]
@ro0NL I do it like `Person` and `Employee` are defined [here](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#single-table-inheritance) except that in my case I've made my base class `abstract`, because it makes no sense whatsoever to ever instantiate my base class.

Does that make sense?

**Comment by ro0NL** [comment]
Thx. Ill have a look soonish what reading the discriminator map brings. In general it exposes the mapped class we need.

However an issue comes with the entity factory, for a new entity we need to know the discriminator value.

**Comment by ro0NL** [comment]
@Evertt i think single table inheritance works out-of-the-box already no? Given we know about your base class and use it with doctrine... Also the same goes for class table inheritance i guess.

Not able to play with various scenarios yet, but AFAIK doctrine will return one of your sub classes based on the discriminator value.

Leaning to close this issue as supporting multiple, independent, user entities in the _bundle_ is not worth it IMHO. In PHP this is easy to do anyway.

**Comment by Evertt** [comment]
I guess you're right? I haven't tried it yet to be honest, but yeah, if the user provider automatically supports multiple entities then we're done here. :-)

**Comment by ro0NL** [comment]
Ok. I remember what its about; factorizing the entity (i.e. `user:create`). We need to know a discriminator value to get the concrete class.
