### ISSUE TITLE
[Question] User Validation example

### ISSUE THREAD

**Issue by dvc** [msgphp/msgphp#74]
I want to create some custom steps as CommandHandlers with CreateUserHandler as main handler:

- customize defaults (generate password if empty, set custom roles if some conditions, set enable by default, etc ). 
- do validation (credential_email is valid email for example, unique and required fields)
- show some messages (generated plain password)

But CreateUserHandler does create entity, bind context and persist in one step. Without validation.

Can you recommend a best practice for my case?

Thank you! :)

**Comment by ro0NL** [comment]
Hi!,

You're ahead of me :) For now the validation happens where needed (e.g. after form submit) meaning you're responsible for initializing a valid command message. Which is the best practice for now, or the most simple one at least.

Currently there's no built-in feature (therefor as a consequent CLI for example doesn't validate, which is kinda based on the assumption you pass valid data anyway).

Alternatively you could configure validation constraints for the command message itself, and then simply validate the object as a whole before dispatching, using the symfony validator service.

In theory there could be some message middleware to validate messages commands out-of-the-box, e.g.  `ValidatingMessageMiddleware` and throw `InvalidMessageException` or so in case it's invalid;  practically wiring symfony/validator :)

About customizing defaults: i'd say that's a factory job.

**Comment by dvc** [comment]
Thank you, @ro0NL ! 

Validate Command DTO - is the best for me. And set defaults in it too.

So, if i'll transform MyCreateUserCommand->toCreateUserCommand(), i can use default workflow after that.
