### ISSUE TITLE
Hook up with new SF message component

### ISSUE THREAD

**Issue by ro0NL** [msgphp/msgphp#8]
See https://github.com/symfony/symfony/pull/24411

`CommandBusInterface::handle + EventBusInterface::handle` => `MessageBusInterface::dispatch`

decide path for https://github.com/msgphp/user-bundle 

- 3.4 => SimpleBusCommandBusBundle + SimpleBusEventBusBundle
- 4.1 => MessageBundle/FrameworkBundle

idea is to detect message component first, if available use that for wiring. Otherwise wire current simplebus bundles.

@sroze do you know if the simplebus bundles become deprecated once a new message component/bundle is here?

**Comment by sroze** [comment]
I'd say so. There is no plan yet, it's not even merged within Symfony's Core. If it is merged, we need to have a discussion with SimpleBus' maintainers and decide whether it makes sense to keep maintaining both :)

**Comment by ro0NL** [comment]
It happened :) https://github.com/symfony/symfony/pull/24411

We need to raise an issue over at SimpleBus to see if it's worth keep supporting.
